foundry-rs/book

src/getting-started/readme.md

I think this fixes the 404 link in the getting started page not pointing correctly to `first-steps.md`

Fix broken link in getting-started

---

src/reference/ds-test.md

The [ds-test reference](https://github.com/onbjerg/foundry-book/blob/ec66dbc1284f938cbbdeadf3b1bb0c35f3f5813c/src/reference/ds-test.md) mixes up the definitions of `assertGe` & `assertGt` and also those of `assertLe` & `assertLt`.
Fixed after verification against [this](https://github.com/dapphub/ds-test/blob/0a5da56b0d65960e6a994d2ec8245e6edd38c248/src/test.sol) implementation

Fix assert definitions in ds-test reference

---

src/reference/cast.md
src/reference/index.md

I noticed most of the `wallet` commands were not documented while working on https://github.com/gakonst/foundry/issues/790
Add docs for all the `wallet` commands

Docs for `wallet` commands

---

src/forge/fuzz-testing.md

Make it easier to see how to restrict the amount, reading fast is easy to miss the change from uint256 to uint96. Personally, I was looking into the `//snip comment` and trying to find a previous function or one it the cheatcodes  with that name. 
TLDR: Makes it easier to understand for noobies like me

docs: add clarity in restrict fuzz amount to 2*96 wei

---

src/forge/writing-tests.md
src/reference/cheatcodes.md

Add docs for https://github.com/brockelmore/forge-std/blob/master/src/stdlib.sol#L78-L88

docs: add forge-std's deployCode

---

src/index.md

This Pull Request adds a link to the Awesome Foundry GitHub repo by Cris Garner. Closes #25

docs: add reference to Awesome Foundry repo

---

src/reference/cheatcodes.md

I refer to the Cheatcodes reference page often and I believe the whitespace (or lack thereof) on the [Cheatcodes Interface section](https://onbjerg.github.io/foundry-book/reference/cheatcodes.html#cheatcodes-interface) could be improved.
Summary of proposed changes:
1. I initially just wanted to add a blank line between each function, but after doing that I thought it looked better with the function definition comment was below the function sig line.
2. In performing this, I noticed a definition comment was missing for `getCode()` so I added it
3. My grammar checker also caught a very minor grammar fix

Fix: Cheatcodes Interface whitespace

---

src/reference/cheatcodes.md

label() is missing data location for name param elicits:

docs: label name param data location = calldata

---

src/reference/cheatcodes.md

- Remove requirement for not checking values in batched events
- Add best practice comment on defining the event ourselves if it's not in-scope.
This is based on what I learned in the recent uniswap v3-periphery migration

Update expectEmit reference

---

src/forge/writing-tests.md

Fix checksum for test contract address. You can verify this checksum by navigating to https://etherscan.io/address/0xb4c79dab8f259c7aee6e5b2aa729821864227e84 and comparing the address (case-sensitive) that Etherscan displays with the address casing in this PR.

Fix checksum for test contract address

---

src/forge/deploying.md

This adds some additional text and trouble shooting tips around finding the `compiler-version` commit argument to pass to `forge verify`

docs: add help for finding compiler commit

---

src/README.md
src/guides/README.md

Noticed that incremental adoption readme was missing so I updated the links where necessary.

update broken incremental adoption links in readme

---

src/forge/deploying.md

Updated the Deploying and Verifying page to clarify part of the CLI parameter and to specify that `forge create` can only deploy one contract at a time.

Added clarifying info about forge create

---

src/reference/cheatcodes.md

Fixes
Note this function signature already includes `calldate` [here](https://github.com/onbjerg/foundry-book/blob/bcc23b30a453692240f7f38491f603064f24daa1/src/reference/cheatcodes.md?plain=1#L90)

Add calldata to label function signature

---

src/tutorials/solmate-nft.md

I am writing a Docker tutorial that builds off the awesome solmate tutorial currently in the foundry book. While writing it, I noticed a few minor bugs in the NFT tutorial:
1. Does not explicitly instruct user to install openzeppelin dependencies
2. The "Basic NFT" won't actually compile because it does not implement the `tokenURI` function from Rari's ERC721 abstract contract.
I just made a couple edits to address these small "bugs".

small fixes to solmate nft tutorial

---

src/reference/config.md

I fat-fingered this in https://github.com/onbjerg/foundry-book/pull/91
Docs confirming this is the correct default: https://docs.rs/proptest/latest/proptest/test_runner/struct.Config.html#structfield.max_local_rejects

fix wrong default number in config

---

src/forge/cheatcodes.md
src/forge/deploying.md
src/forge/fuzz-testing.md
src/tutorials/solmate-nft.md

Since v0.6.8, the Solidity compiler started throwing the following warning when an SPDX identifier is missing from a contract:
> SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
Since the Foundry Book should not decide on behalf of the end users what license to use, I set the SPDX to [UNLICENSED](https://docs.soliditylang.org/en/v0.8.13/layout-of-source-files.html#spdx-license-identifier).

Add UNLICENSED SDPX identifier

---

src/tutorials/solmate-nft.md

The main problem is that the `nft-tutorial` hyperlink has an extra parenthesis (`(`), which causes the link to show up like this:

fix: typos in NFT tutorial

---

src/forge/cheatcodes.md
src/forge/deploying.md
src/forge/fuzz-testing.md
src/reference/cheatcodes.md
src/tutorials/solmate-nft.md

The Solidity code snippets are inconsistent in the number of spaces they use for indenting.
Since the Solidity docs [recommend using 4 spaces](https://docs.soliditylang.org/en/v0.8.13/style-guide.html?highlight=4%20spaces#indentation), I changed all code snippets in the Foundry book to follow this recommendation.

style: indent solidity code snippets with 4 spaces

---

src/forge/debugger.md

I added a line on the debugger tab explaining how to debug more complex functions (ones with a constructor or need a certain state)
I found this not to be obvious when I first started using foundry so I thought it may be useful to someone in the future

debugging complex functions

---

src/SUMMARY.md
src/getting-started/installation.md
src/tutorials/dockerize-solmate-nft.md
src/tutorials/foundry-docker.md

This is a write-up of the Docker installation instructions and a walkthrough of how to use foundry within docker. It covers:
- Basic Installation
- Direct Interfacing w/ `forge` and `cast` through Docker
- Live developing in Docker using `--watch`
- Building custom images on top of the Foundry image
There will likely be more to add later, but this covers a good first portion.

Foundry and Docker Section

---

src/reference/cast.md

Adds `cast proof` to cast reference. Closes #52

docs: add cast proof to cast reference

---

src/forge/writing-tests.md
src/reference/cast.md

Points to following section on cheatcodes in `Writing Tests` for working with cheatcodes. Closes #143

docs: add reference to following section for cheatcodes

---

src/forge/fuzz-testing.md

fix link to assume in fuzz testing docs.

docs: fix assume reference link in fuzz testing docs

---

src/tutorials/foundry-docker.md

typo in [Creating a deployer iamge](https://book.getfoundry.sh/tutorials/foundry-docker.html#creating-a-deployer-iamge) header

fix: typo, iamge -> image

---

src/forge/forking-mode.md

I was trying to get etherscan traces on a repo I owned and noticed the docs did not have a clear explanation as to how to do it. I put it as a `tip` in the forking section as I figured that was the location where it was likely to help the most developers. Let me know if I need to make any changes.

docs: add instructions on how to get etherscan traces

---

scripts/generate-output-cast
src/output/cast/cast-call

`cast call` example didn't have function name as string

docs: fix `cast call` example command

---

src/forge/differential-ffi-testing.md

In case there are more questions like this: https://github.com/foundry-rs/book/pull/225#issuecomment-1110069116.
Also not sure if this would be useful in something like `forge-std` to help people with ffi testing? Happy to clean up the library and open a pr if we think it's useful.

Differential Testing: add link to Strings2 library for converting bytes to hex string

---

src/cheatcodes/ffi.md
src/forge/forge-std.md
src/reference/README.md
src/reference/forge-std/README.md
src/reference/forge-std/std-math.md

1) The ffi link was broken. I redirected it to the place it should go for, which is https://book.getfoundry.sh/reference/config.html#ffi
2) Added the Forge Standard Library Reference name and link to the References part

Fixed links and added "Forge Standard Library Reference" to references

---

src/projects/dependencies.md

I've been nonchalantly using `forge install` for some time now only to recently discover that it had been clogging up my git commit history.

Add note about git commit created by "forge install"

---

src/reference/cast/cast-4byte.md
src/reference/common/wallet-options-raw.md

- 4byte example said abi-decode
- mnemonic was spelled wrong

Fixed two small typos in cast reference

---

src/forge/differential-ffi-testing.md

In the [Differential Testing](https://book.getfoundry.sh/forge/differential-ffi-testing.html#differential-testing) section, remove duplicate wording in "uses of uses of this type of testing" .

Fixe duplicate in "uses of uses of" wording in Differential Testing section

---

src/forge/differential-ffi-testing.md

Adding with permission from @patrickd-. This is a great template for Echidna+Foundry fuzzing and differential fuzzing.

Differential Testing: add patrickd-'s fuzzing template as a reference

---

src/reference/forge/forge-test.md

fixes: https://github.com/foundry-rs/book/issues/306
didn't add the `--list` flag to `{{#include ../common/display-options.md}}` because looks like only `forge test` has it

docs: add forge test --list

---

src/forge/debugger.md

`forge test` has an `--match-path` option but the Foundry book spells it incorrectly as `--match-patch` here.

debugger.md: s|--match-patch|--match-path|

---

src/reference/config.md

fixes: https://github.com/foundry-rs/book/issues/313
1. Would like some feedback on the configuration keys
2. I left the following commented out in the `toml` like `#solc_version`
- wasn't sure how to represent `None` in toml
```toml
#optimizer_details = None
#eth_rpc_url = None
#etherscan_api_key = None
#test_pattern= None
#test_pattern_inverse = None
#contract_pattern = None
#contract_pattern_inverse = None
#path_pattern = None
#path_pattern_inverse = None
#block_gas_limit = None
```

docs: add missing config reference

---

src/reference/forge/forge-verify-contract.md

The 'Deploying' section had the meaning of `x` and `y` for the command `~/.svm/x.y.z/solc-x.y.z --version`, but the forge verify reference didn't. It caused a bit of confusion for me, hence I hope this PR can help others avoid the confusion in the future.

docs: Add meaning of x and y in forge verify reference

---

src/forge/deploying.md
src/reference/forge/core-build-options.md
src/reference/forge/forge-create.md
src/reference/forge/forge-verify-contract.md
src/reference/forge/project-options.md

closes: https://github.com/foundry-rs/book/issues/323
closes: https://github.com/foundry-rs/book/issues/236
I added 2 missing flags `--delay` and `--retries`from 
```sh
forge verify-contract -h
```
I also saw 2 missing options from `project-options`
```sh
--remappings-env
--config-path
```
It looks like `forge-flatten` and `forge-tree` also use `{{#include project-options.md}}`
- and it shows up on their `-h`

docs: update verify documentation

---

src/cast/README.md

Adds an example of using `cast send` to send an arbitrary message.
Note: I wasn't sure how to run `anvil` in the background so that the command output could be generated rather than hard-coded. If anyone has pointers on that, please let me know. Related: https://github.com/foundry-rs/book/issues/173

docs: add example of cast send message

---

src/reference/forge/compiler-options.md

AFAICT they take the same values, "Valid values" is ambiguous as to whether it's a comprehensive list

docs: minor copyedit of `--extra-output-files`

---

src/anvil/README.md

Mainly adding the note on re-installing foundryup for users on older versions. Also a typo fix or two and some re-wording.

Minor changes to anvil overview readme

---

src/reference/anvil/README.md

debug_traceTransaction not supported yet
https://github.com/foundry-rs/foundry/issues/1737

fix: remove unsupported debug_traceTransaction

---

Dockerfile
README.md

This PR adds a Dockerfile to start `mdbook`. 
I saw that the the main book URL [was down](https://twitter.com/gakonst/status/1542175547731480583) and I wanted to spin up a mirror.

chore: adds Docker setup instructions

---

src/forge/deploying.md

The etherscan-api-key flag is missing, which leads to an error when you copy paste the commands without including it

Add etherscan-api-key flag

---

src/config/hardhat.md

Add a 4-step instruction to add foundry to an existing hardhat project in `config/hardhat.md`

add foundry to an existing hardhat project

---

src/forge/writing-tests.md

This PR does two things:
1. Adds a note about the function visibility requirements for test functions.
2. Improves the formatting of the code snippets in `writing-tests.md`.

Add note about test function visibility

---

src/reference/forge/project-options.md

In regards to #430 I added `--build-info` and `--build-info-path` to the book's reference section. I took the options and the description from the `forge build --help` output and added it in.

#430 build-info and build-info-path options to the reference section

---

src/README.md
src/SUMMARY.md
src/misc/README.md
src/reference/cast/cast-sig.md

- Links to `misc/struct-encoding.md` are incorrect
- Some links on the cover are incorrect
- The cover is out of date
- Fix links
- Update the cover

docs: update cover

---

src/config/README.md

Using underscores makes numbers more readable.

Use underscore in "optimizer_runs"

---

src/reference/cast/cast-send.md

correction of order in `EXAMPLES`(#3)

---

src/reference/anvil/README.md

these commands will be added to the main CLI https://github.com/foundry-rs/foundry/pull/2256 , so this PR brings the docs into parity.

add docs on `anvil_dumpState` and `anvil_loadState`

---

src/SUMMARY.md
src/faq.md
src/reference/forge-std/README.md
src/reference/forge-std/console-log.md

Document console.log string format specifiers implemented in https://github.com/foundry-rs/foundry/pull/2313.

Document console.log format specifiers

---

src/cheatcodes/README.md

Hi,
I have made some revisions to the `cheatcodes` section following [this discussion](https://twitter.com/0xArbiter/status/1550126535440379911) on Twitter with Bjerg.
I felt that there wasn't sufficient documentation surrounding the forge-std 'cheatcodes', which was weird considering they're meant for DX improvements.
- Refactored parts of the document to make it easier to read
- Added in a section explaining how to exclude the cheatcode address from fuzz testing (this and the precompile addresses personally cost me 3 days of dev time when I was learning Foundry, luckily a fellow dev explained what I needed to do)
- Added a link to the Forge Standard Library 'cheatcodes' directly from this document
- Added a link to the forge-std GitHub for those who want to see how the 'cheatcodes' work …

Cheatcode Documentation Revision

---

src/getting-started/installation.md
src/tutorials/solmate-nft.md

When I installed the binaries using `foundryup`, I received three binaries.
```
$ foundryup
foundryup: installing foundry (version nightly, tag nightly-64fe4acc97e6d76551cea7598c201f05ecd65639)
foundryup: downloading latest forge, cast and anvil
######################################################################### 100.0%
foundryup: downloading manpages
######################################################################### 100.0%
foundryup: installed - forge 0.2.0 (64fe4ac 2022-07-26T00:04:05.891537523Z)
foundryup: installed - cast 0.2.0 (64fe4ac 2022-07-26T00:04:05.891537523Z)
foundryup: installed - anvil 0.1.0 (64fe4ac 2022-07-26T00:04:04.746772497Z)
foundryup: done
```
I updated the book to reflect that.

Fix installation page

---

src/output/hello_foundry/tree
src/output/hello_foundry/tree-with-files

Updating the output of the `tree` command to include the new `script` directory and file.

updating output to include the script directory and file

---

src/config/hardhat.md

Link to remapping-dependencies was broken. Link to config was pointing to the html page.

fix: links

---

src/reference/anvil/README.md

References
|__ anvil Reference 
|__ EXAMPLES 
|__  Codeblock for point number 1  missing a backtick , that has been added, its not a major issue , just when copying the block directly, generates some errors.

docs: References-anvil Reference - Examples - missing backtick in codeblock

---

src/SUMMARY.md
src/cheatcodes/project-root.md

Adds a page for the cheatcode added in https://github.com/foundry-rs/foundry/pull/2762
This PR closes https://github.com/foundry-rs/book/issues/523
Simple feature, so not much to say here.

Add projectRoot cheatcode page

---

src/config/static-analyzers.md

Changes to -  `https://github.com/foundry-rs/book/blob/master/src/config/static-analyzers.md`
Addition of descriptive text and correct syntax for the usage of `slither` with a custom `file-config.json` and also includes the raw ouput, after a new repository has initialized with `forge init`

Fix Slither Static Analyzer Config Json usage syntax

---

src/faq.md

Ref https://github.com/foundry-rs/foundry/issues/2714
symlinks are kinda cursed, luckily solc can handle them but if they're pointed outside the foundry workspace we need to add `allow_paths`

docs: add monorepo troubleshooting section

---

src/projects/dependencies.md

Contracts in forge projects are in the `src` directory. Would be clearer to say that instead of the word "source".

fix: clarify default location for contracts

---

src/reference/anvil/README.md

The `--block-gas-limit` flag doesn't seem to work as a CLI argument for anvil (at least on macOS). The `--gas-limit` flag works and is already included below. This PR just removes mention of `--block-gas-limit`.

Remove --block-gas-limit from README.md

---

src/forge/fork-testing.md

line 195 simple.value() needed a ; at end of line to compile
little typos here and there:
'therefor' -> 'therefore'
'contract does not exists' -> 'contract does not exist'
'contract only lifes in "mainnetFork"' -> 'contract only lives in "mainnetFork"'
persitent -> persistent

Fixed code snippet that doesn't compile, typos

---

src/SUMMARY.md

fix: add missing link

---

src/cheatcodes/README.md

4 typos fixed, all the same: 'mnenomic' -> 'mnemonic'
BTW, love the cheatcodes! Comprehensive, concise, and useful.

Fixed spelling error in solidity snippet

---

src/output/cheatcodes/forge-test-cheatcodes-tracing
src/output/cheatcodes/forge-test-simple
src/output/deps/forge-install
src/output/deps/forge-remappings
src/output/femplate/forge-build
src/output/femplate/forge-test
src/output/forge_tree/forge-tree
src/output/forge_tree/forge-tree-no-dedupe
src/output/fuzz_testing/forge-test-fail-fuzz
src/output/fuzz_testing/forge-test-no-fuzz
src/output/fuzz_testing/forge-test-success-fuzz
src/output/hello_foundry/forge-build
src/output/hello_foundry/forge-init
src/output/hello_foundry/forge-test
src/output/hello_foundry/tree-with-files
src/output/nft_tutorial/forge-test
src/output/test_filters/forge-test-match-contract-and-test

Related https://github.com/foundry-rs/foundry/pull/2640, https://github.com/foundry-rs/forge-std/pull/168
EDIT: After opening this PR (to update `tree-with-file`), I noticed that the `generate-output` command existed in `scripts`, so I ran it and picked and updated only the essential changes additionally, i.e. excluding changes of compile time.

Update command outputs

---

src/reference/forge-std/assertApproxEqAbs.md

The signatures of the 2 "assertApproxEqAbs" had a duplicate

Remove duplicate of function signature

---

src/config/shell-autocompletion.md

When running the commands:
```sh
forge completions zsh > /usr/local/share/zsh/site-functions/_forge
cast completions zsh > /usr/local/share/zsh/site-functions/_cast
anvil completions zsh > /usr/local/share/zsh/site-functions/_anvil
```
I get this error:
```sh
zsh: no such file or directory: /usr/local/share/zsh/site-functions/_forge
zsh: no such file or directory: /usr/local/share/zsh/site-functions/_cast
zsh: no such file or directory: /usr/local/share/zsh/site-functions/_anvil
```
See: https://stackoverflow.com/questions/65747286/zsh-problem-compinit503-no-such-file-or-directory-usr-local-share-zsh-site
The autocomplete on ARM-based systems are not stored in the same directory.

Update shell-autocompletion.md for M1 machines

---

src/reference/cast/cast-send.md

Closes #551 by documenting `cast send --create` option to deploy raw contract bytecode

document cast send create

---

src/config/static-analyzers.md

Minor update: renamed `slither-config.json` to `slither.config.json` for completion.

Updated slither default file-name

---

src/reference/forge-std/assertEq.md

Usage example was incorrect in #639 (`assertUint128Eq` does not exist).

docs: correct example

---

src/reference/forge/compiler-options.md

I met an error
```
error: Found argument '---extra-output-files' which wasn't expected, or isn't valid in this context
Did you mean '--extra-output-files'?
```

remove redundant dash from ---extra-output-files

---

src/config/hardhat.md

The hardhat preprocessor snippet will apply multiple transformations on a single line with an import statement. This becomes an issue when multiple matching substrings appear in an import statement.
Consider the following repo:
```ignore
openzeppelin-contracts/=lib/openzeppelin-contracts/
contracts/=src/ # a convenience import remapping
```
and the import statement
```solidity
import "openzeppelin-contracts/contracts/token/ERC20/extensions/draft-ERC20Permit.sol";
```
expected output:
```solidity
import "lib/openzeppelin-contracts/contracts/token/ERC20/extensions/draft-ERC20Permit.sol";
```
actual
```solidity
import "lib/openzeppelin-src/contracts/token/ERC20/extensions/draft-ERC20Permit.sol";
```
___
This change proposes that the preprocessor loop `breaks` after finding a matching …

docs: update hardhat snippet

---

src/reference/config/testing.md

The `vm.rpc` link in https://book.getfoundry.sh/reference/config/testing#rpc_endpoints is broken. Just fixed it.

fix broken link of `vm.rpc`

---

src/reference/forge/forge-verify-contract.md

The modifier previously used `--constructor-args` with a file as input, but the correct usage in this instance is `--constructor-args-path` because it will use the file correctly.

Correct Invalid command in directions

---

src/reference/common/display-options.md
src/reference/common/verifier-options.md
src/reference/common/wallet-options-hardware.md
src/reference/common/wallet-options-raw.md

This PR updates some of the documentation for command line options to be in line with the current release of foundry.
Closes #650. 
Also has some extra little fixes (mostly for wallet-related options), but I absolutely did not get every discrepancy.
From what I saw, I think the best approach might be to have someone eventually implement a bash script that autogenerates docs from parsing the output of various `--help` calls, and plug that into CI... the docs have diverged very significantly from what's actually in the binary, and it'd be such a headache to have people keep manually updating them...

Small docs options updates.

---

src/reference/cast/cast-index.md

The example provided in the book returned an error

Fix cast index example

---

src/tutorials/solidity-scripting.md

Openzepplin changed its contract structure. The original code is:
```solidity
import "openzeppelin-contracts/contracts/utils/Strings.sol";
import "openzeppelin-contracts/contracts/access/Ownable.sol";
```
which will cause error when using `forge build`:
```shell
Compiler run failed
error[6275]: ParserError: Source "lib/openzeppelin-contracts/contracts/contracts/utils/Strings.sol" not found: File not found. Searched the following locations: "/Users/liang/Documents/Fight for PHD/work/MiniSolidity/Code/Test/solidity-scripting".
--> src/NFT.sol:4:1:
|
4 | import "openzeppelin-contracts/contracts/utils/Strings.sol";
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[6275]: ParserError: Source "lib/openzeppelin-contracts/contracts/contracts/access/Ownable.sol" not found: File …
```

Fix bug that causes Compiler run failed when forge build

---

src/reference/cast/cast-balance.md

fix: typo in cast balance

---

src/tutorials/solidity-scripting.md

- update for Goerli since Rinkeby is deprecated
- update .env reference to ETHERSCAN. Verification only succeeds using ETHERSCAN_API_KEY; not ETHERSCAN_KEY
The ETHERSCAN_API_KEY is the only important part. I couldn't get verification to succeed with the provided forge script
```sh
forge script script/NFT.s.sol:MyScript --rpc-url $GOERLI_RPC_URL --broadcast --verify -vvvv
```
unless I changed `ETHERSCAN_KEY` -> `ETHERSCAN_API_KEY`, which makes it consistent with the rest of the book.

Update Scripting tutorial for Goerli & fix ETHERSCAN_API_KEY

---

src/reference/anvil/README.md

fixes: https://github.com/foundry-rs/book/issues/671
added anvil flags
--config-out
--steps-tracing
--code-size-limit
--prune-history

docs: add missing anvil flags

---

src/reference/cast/cast-index.md

It seems that value_type is not a valid argument for `cast index`. 
`cast index -h` gives me:
Compute the storage slot for an entry in a mapping.
Usage: cast index <KEY_TYPE> <KEY> <SLOT_NUMBER>
Arguments:
<KEY_TYPE>     The mapping key type.
<KEY>          The mapping key.
<SLOT_NUMBER>  The storage slot of the mapping.
Options:
-h, --help  Print help information

remove value_type from arguments

---

src/reference/forge-std/startHoax.md

i'm not really sure but when i was using hoax(addr) it wasn't the addr that was owning the contract

add precision

---

src/forge/deploying.md

`forge verify-contract` supports 3 ways of verifying the contract, but in `deploying.md` only Etherscan is mentioned.
I personally initially thought that `forge` supports only etherscan, but then I went to `verify-contract` docs, where I could find, that there are also 2 more verifiers supported

Added other explorers in deploying.md

---

src/tutorials/solmate-nft.md

already remapped: 'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'.

Update import statement of openzepplin-contracts

---

src/reference/config/testing.md
src/static/config.default.toml

Updates with the new default address: `0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38`.
Ref/Pending: https://github.com/foundry-rs/foundry/pull/3680

Update new default sender address

---

src/getting-started/installation.md

I use Windows, and I encountered this installation issue. Windows users who do not have the VS Code Installer would not be able to successfully install Foundry. I just fixed that in this edit.

Added Rust.exe and VS Code Installer for Windows

---

src/cheatcodes/env-string.md

Update documentation for envString

---

src/getting-started/installation.md

when i type `foundryup` on macOS. It display below error. In my opion, i add a tip to slove below error.
```sh
foundryup: installing foundry (version nightly, tag nightly-b28119b56d7dd18c268a471167a0c547c301c13e)
foundryup: downloading latest forge, cast and anvil
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
foundryup: command failed: curl -# -L https://github.com/foundry-rs/foundry/releases/download/nightly-b28119b56d7dd18c268a471167a0c547c301c13e/foundry_nightly_darwin_amd64.tar.gz
foundryup: downloading manpages
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
foundryup: command failed: curl -# -L https://github.com/foundry-rs/foundry/releases/download/nightly-b28119b56d7dd18c268a471167a0c547c301c13e/foundry_m …
```

update src/README.md. Add a tip for macOS

---

src/reference/cast/cast-send.md

Reference was pointing to a dead end with 404.

update reference to struct encoding in cast-send

---

src/SUMMARY.md
src/cheatcodes/README.md
src/cheatcodes/env-or.md
src/cheatcodes/external.md

Docs to envOr cheatcode
Description: Issue https://github.com/foundry-rs/foundry/issues/3732
Implementation merged at: PR https://github.com/foundry-rs/foundry/pull/3810
Docs can be merged after the Vm interface (PR: https://github.com/foundry-rs/forge-std/pull/249) is merged to forge-std

docs: add envOr cheatcode docs page

---

src/reference/anvil/README.md

closes: https://github.com/foundry-rs/book/issues/721
included the debug_traceTransaction method  together with a statement that the --steps-tracing is required to get structLogs

docs: add debug_traceTransaction method

---

src/cheatcodes/expect-revert.md

I tested with Solidity v0.8.17
1. The current argument name `msg` throws the following compiler warning:
> Warning: This declaration shadows a builtin symbol
2. `expectRevert("AAAA")` cannot be compiled at all:
> TypeError: Member "expectRevert" not unique after argument-dependent lookup in contract Vm.
3. There is no need to cast the string literals to `bytes()`. The compiler works just fine without the cast.
4. There is no need to wrap the string literals in `abi.encodePacked` in the final example.

Improve documentation for "expectRevert"

---

src/cheatcodes/start-broadcast.md

The keyword 'cheats' doesn't work with the last version of Foundry, it should be replaced by 'vm' in the doc

Corrected 'cheats' to 'vm'

---

src/tutorials/best-practices.md

There is now a dedicated YouTube URL for Rikard Hjort's presentation [Formal Methods for the Working DeFi Dev](https://www.youtube.com/watch?v=ETlNhV9jYJw) from Devcon 6.

Update Devcon video URL

---

src/tutorials/best-practices.md

To my knowledge, PRBMath is currently the most proficient Foundry-based repo in terms of number of [table tests](https://github.com/foundry-rs/foundry/issues/858). I have taken the approach suggested [here](#issuecomment-1078427963), i.e. to parameterize tests using a struct and a modifier, to its limits.

Mention PRBMath in "Foundry in Action"

---

src/tutorials/solidity-scripting.md

After #727, the links to the images in the Solidity Scripting tutorial were broken.
This should fix it.

Fix `solidity-scripting.md` tutorial

---

src/reference/config/formatter.md

The [Formatter](https://book.getfoundry.sh/reference/config/formatter) guide is outdated. It references a key that no longer exists (`func_attrs_with_params_multiline`), which was replaced in https://github.com/foundry-rs/foundry/pull/3252 by `multiline_func_header`.
This PR updates the formatter guide to contain the most up-to-date configs, noting that I have sourced the English descriptions from the [`fmt.rs`](https://github.com/foundry-rs/foundry/blob/be7084e74247a9880c4357d444143d03fc2269e5/config/src/fmt.rs) file. For `ignore`, I have assumed that the globs are comma-separated, but I am not sure about that.

Update Formatter guide with latest configs

---

src/tutorials/solidity-scripting.md

The command is either `anvil --mnemonic` or `anvil -m`, never `anvil --m`.

fix: delete extra hyphen in anvil script

---

src/faq.md

I asked there https://github.com/foundry-rs/foundry/issues/4044 before.
I have written the solution in `faq.md`, hoping to help developers who are in China.
I'm a college student in China and so glad to contribute.

Add FAQ for connection failure when access may be restricted

---

src/config/static-analyzers.md

I tried running Slither on a specific contract, as currently suggested in the Foundry Book:
```sh
slither src/MyContract.sol
```
However, this failed with the following error:
> crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found:
I double-checked that the Solidity compiler was installed correctly `solc-select`, as indicated in the book. 
The only thing made Slither work was to run `slither .` instead. This is also what's [recommended](https://github.com/crytic/slither/tree/7ea572723b4eddb18e716c4ae94e0d2100791127#bugs-and-optimizations-detection) in their README.
The following gets logged as soon as I run `slither .`, suggesting that Slither is aware that my project is a Foundry project and it compiles the code with Forge:
```text
'forge build --extra-output …
```

Fix Slither command

---

src/tutorials/testing-eip712.md

Dynamic values of the EIP-712 struct hash (ie bytes and string types) must be encoded as a keccak256 hash of their contents. However since this tutorial codebase doesn't involve any bytes/string dynamic values, that aspect of 712 is not covered at all. It should be mentioned since it can confuse devs like me writing eip712 meta-tx contracts.
I wrote a brief informative blurb explaining why it's not shown here, why it's relevant regardless, and then linking to the exact line of the EIP spec gh repo where this is discussed.

Eip-712 section should cover byte/string encoding

---

src/cheatcodes/parse-json.md

Probably a typo introduced by commit 9acb7f2d4a3682215f9b1e8b234b4e39d47cbfcd

fix: Markdown formatting on parse-json.md

---

src/config/static-analyzers.md

As indicated by a Slither maintainer in this [comment](https://github.com/crytic/slither/issues/1421#issuecomment-1383280980), Foundry users don't have to provide the remappings via the `solc_remaps` option anymore. Slither automatically detects the remappings in a Foundry project now.

Remove "solc_remaps" in Slither config

---

src/reference/chisel/README.md

`mdbook test` is currently failing due to unannotated code blocks in `chisel` docs

Fix `chisel` docs

---

src/config/vscode.md

Hello,
The Solidity extension by JuanBlanco seems to have updated, and the default formatter for the solidity language on VSCode now accepts `JuanBlanco.solidity` instead of `JuanBlanco.vscode-solidity`
Thanks.

Update VSCode Default Formatter

---

src/reference/config/testing.md

The current wording is a bit ambiguous - it's not clear if the reference is about the user's own reentrancy checks, or if Foundry performs the reentrancy checks by setting `call_override` to `true`.

Be more specific in "call_override" explainer

---

src/reference/config/testing.md

Fixes https://github.com/foundry-rs/foundry/issues/4257.

Improve wording for `[fuzz]` and `[invariant]` explanations

---

src/reference/config/testing.md

The config variable names in the documentation do not work for matching tests/contracts/paths when trying to run tests. 
The naming that works is the same as the command line flag (e.g. `match-contract` rather than `contract-pattern`).
This PR changes those variable names in the documentation, both for the foundry.toml config and the ENV variables referenced:
- `test-pattern` -> `match-test`
- `test-pattern-inverse` -> `no-match-test`
- `contract-pattern` -> `match-contract`
- `contract-pattern-inverse` -> `no-match-contract`
- `path-pattern` -> `match-path`
- `path-pattern-inverse` -> `no-match-path`
- `_TEST_PATTERN ` -> `_MATCH_TEST`
- `_TEST_PATTERN_INVERSE` -> `_NO_MATCH_TEST`
- `_CONTRACT_PATTERN ` -> `_MATCH_CONTRACT`
- `_CONTRACT_PATTERN_INVERSE` -> `_NO_MATCH_CONTRACT`
- …

Fix variable names used in config for test matching

---

src/tutorials/best-practices.md

Per https://github.com/foundry-rs/forge-std/pull/290, failed assertions now use `left` and `right` like rust assertions, so this is now outdated 
(technically this is not true until forge-std v1.5.0 is released, which I'm planned to do later today)

remove actual/expected, now left/right is used

---

src/reference/anvil/README.md

Hi, 
I wanted to use `debug_traceCall` with `tracer = 'callTracer'`, and based on this PR, https://github.com/foundry-rs/foundry/pull/3990, I thought it might be supported.
Alas, I'm getting a blocking error `non-default tracer not supported yet`. 
I'm sending this PR to the docs to either help future users and/or get clarity myself.
I'm a bit confused by...
```
if opts.tracer.is_some() {
return Err(RpcError::invalid_params("non-default tracer not supported yet").into())
}
```
Does this mean `tracer` cannot be set at all?  
Should I be able to use  `debug_traceCall` in Avil against a forked mainnet, *on an unmined transaction*?

Update anvil docs given `debug_traceCall`

---

src/forge/deploying.md

Fix verify contract syntax
- Wrong syntax for --etherscan-api-key
- Split to multiple lines

Fix verify-contract example

---

src/forge/invariant-testing.md
src/reference/config/solidity-compiler.md

reference for model checker config
relative PRs
- https://github.com/gakonst/ethers-rs/pull/2147
- https://github.com/gakonst/ethers-rs/pull/2123

feat(reference): add model checker config

---

src/cheatcodes/deal.md

`deal` for dealing out ERC20 tokens is out of `StdUtils.sol` and not a native cheat implemented in Foundry itself. @PaulRBerg thanks for the clarification.

`deal` instead of `vm.deal`

---

src/forge/invariant-testing.md

The variables in ExampleContract1 should be public, otherwise compiling in InvariantExample1 will fail.

Fixed the code for the ExampleContract1 contract

---

src/reference/forge/forge-coverage.md

- Created `forge-coverage.md` inside src/reference/forge containing brief overview of the command.
- Examples for each of the `--report` options.
- The `common-options.md` included under reporting options.

forge-coverage overview created

---

src/reference/config/testing.md

Default depth can be double checked here:
https://github.com/foundry-rs/foundry/blob/master/config/src/invariant.rs#L27
Edit:
Commits to foundry-rs changed the line that initializes the default depth. Prev line 30, now it is on line 27.
Default depth is still 15 though.

Fix default depth in invariant runs from 256 to 15

---

src/forge/deploying.md

Kovan has been deprecated.
Change all instances of "kovan" and "42" into "sepolia" and "11155111" respectively.

Update deploying.md, replace kovan with sepolia

---

src/reference/cast/cast-send.md

These links were leading to 404s.

Fix: link to struct encoding in cast send ref

---

src/reference/forge/project-options.md

As title. If you run `forge test --help ` you will see that they changed the shortcuts to capital letters:
```bash
Project options:
--root <PATH>
The project's root path.
By default root of the Git repository, if in one, or the current working directory.
-C, --contracts <PATH>
The contracts source directory
-R, --remappings <REMAPPINGS>
The project's remappings
```

Fix `--contracts` and `--remappings` shortcut in `project-options`

---

src/cheatcodes/README.md
src/cheatcodes/difficulty.md
src/cheatcodes/prevrandao.md

https://github.com/foundry-rs/foundry/pull/4856 followup

docs: Add `prevrandao` cheatcode

---

src/forge/fuzz-testing.md
src/forge/invariant-testing.md
src/reference/config/README.md
src/reference/config/inline-test-config.md

Added documentation for this new foundry feature [#4744](https://github.com/foundry-rs/foundry/pull/4744).

docs: ux fuzz invariant

---

src/reference/anvil/README.md

as a user, I was genuinely confused what were the valid inputs to `anvil --hardfork`, specifically because the example was for the default `latest`. i wasn't sure if it should be capitalized like `Shanghai` or just `shanghai`, or if it didn't matter.
an additionally nice feature could be to improve the error message to not only say `Unknown hardfork shanghai` but `Unknown hardfork shanghai. Currently supported hardforks are london|paris|shanghai|latest` etc., or something in that spirit.

enhance: add clarity to the set of valid inputs for anvil --hardfork

---

src/SUMMARY.md
src/misc/README.md
src/misc/precompile-registry.md
src/reference/forge-std/assume-no-precompiles.md
src/reference/forge-std/assume-payable.md

Adds the precompile registry to document addresses that are either reserved or exhibit potentially unexpected behavior for testing purposes.
Additionally, an entry for `assumePayable` was added.
Previously, these cheats and the precompile addresses appeared to be undocumented.

Add Precompile Documentation and Registry

---

src/tutorials/best-practices.md

- On the best practices page, using `vm.expectEmit(true, true, true, true)` is given, and I thought it would be a good idea to highlight the more concise version `vm.expectEmit()` as well.

Add no args expectEmit to testing best practices

---

src/cheatcodes/sign.md

Wrong placement of argument separator "," `signingExample.purchase()` in function call.

Update `signingExample.purchase()` call in sign.md

---

src/reference/forge/test-options.md

Add `--fail-fast` to `forge test` reference.

docs(forge) add --fail-fast to test reference

---

src/reference/forge-std/assume-no-precompiles.md

Nothing exciting, just a typo.

chore: ✏️ typo in `assume-no-precompiles.md`

---

src/reference/cast/cast-basefee.md

Current behavior:
```
❯ cast basefee
error: unrecognized subcommand 'basefee'
```
Corrected the docs to spell the command as `base-fee` instead

fix: base-fee command docs

---

src/cheatcodes/expect-revert.md

cc @mds1 
This corrects the `expectRevert` docs to now indicate the actual behavior:
- return data is mangled on low level calls and is not usable
- on low level calls, the `status` boolean corresponds to whether the cheatcode succeeded or not, not whether the call succeeded or not.

fix(`expectRevert`): correct expectRevert docs

---

src/reference/cast/cast-storage.md

Recently learned that `cast storage` can be used to return the full storage layout of a contract if verified on Etherscan.
This fact isn't included in the docs, so adding here.

chore: update storage docs to include no slot

---

src/SUMMARY.md
src/cheatcodes/README.md
src/cheatcodes/skip.md

Documents https://github.com/foundry-rs/foundry/pull/5205

feat(`cheatcodes`): add skip cheatcode docs

---

src/reference/cast/utility-commands.md

add create2 to utility commands dropdown
currently doesn't show up per img below

add cast-create2 to utility-commands.md

---

src/tutorials/testing-eip712.md

It should probably be under an open-source license since it's part of the documentation, also upgraded the version to the latest available.

feat: change SPDX identifier to MIT and upgrade pragma version

---

src/reference/forge/forge-inspect.md

This change provides an example using `forge inspect --pretty <contract> abi` included in https://github.com/foundry-rs/foundry/pull/5306

docs: update book to include 'forge inspect --pretty <contract> abi' example

---

src/reference/anvil/README.md
src/reference/cast/cast-from-fixed-point.md
src/reference/cast/cast-to-check-sum-address.md
src/reference/cast/conversion-commands.md

Documents the `--auto-impersonate` flag for Anvil.
Also includes minor fixes to #951

docs: `anvil --auto-impersonate`

---

src/reference/forge/forge-verify-contract.md

I found this option in this issue - https://github.com/foundry-rs/foundry/issues/3507
This was helpful for verifying a contract on Zora's blockscout based explorer.
I don't really know where this standard comes from or anything about it, so hoping someone more knowledgeable is willing to take this over the finish line.

Document forge verify-contract --show-standard-json-input option

---

src/cheatcodes/env-string.md

Replace `cheats` to `vm`, and add string `memory` location in order for the example to work.

Fix env-string.md examples

---

src/reference/common/verifier-options.md
src/reference/forge/forge-verify-contract.md

Documentation to fix Blockscout contract verification bug suggested here:
https://github.com/foundry-rs/foundry/issues/5160#issuecomment-1599602416

feature(`reference`): forge verify contract Blockscout URL bug fix

---

src/cheatcodes/deal.md
src/cheatcodes/etch.md
src/cheatcodes/expect-call.md
src/cheatcodes/sign.md

Deprecate vm.addr() from examples declaring new addresses for 'alice'

---

src/reference/forge-std/assume-no-precompiles.md

There was a breaking change in
https://github.com/foundry-rs/forge-std/pull/407 which renamed `assumeNoPrecompiles()` to `assumeNotPrecompile`.

docs: `assumeNoPrecompiles` -> `assumeNotPrecompile`

---

src/reference/anvil/README.md

Follow up to https://github.com/foundry-rs/foundry/pull/5414

Add ots_* namespace to anvil reference

---

src/reference/forge/forge-snapshot.md

Add a line documenting the `--tolerance` flag for `forge snapshot`.
I used this flag in a CI Action, and a co-worker asked me what it meant since it was undocumented in the Foundry Book.

Add docs for `snapshot --tolerance` flag

---

src/SUMMARY.md
src/cheatcodes/README.md
src/cheatcodes/parse-json-keys.md

Adds docs for parseJsonKeys added in https://github.com/foundry-rs/foundry/pull/5252

Add parseJsonKeys references

---

src/reference/forge/forge.md
src/reference/forge/test-commands.md

`forge coverage` is in the sidebar, but not sometimes in the main copy. This adds a few links where it seems appropriate.

Add more links in docs for forge coverage

---

src/tutorials/solmate-nft.md

In this pull request, I've addressed the issue where the NFT tutorial tests were utilizing the older version of the etch cheatcode. The behavior of the etch cheatcode was recently altered in [foundry-rs/foundry#4905](https://github.com/foundry-rs/foundry/pull/4905), making the existing NFT tutorial tests incompatible.
- Updated the NFT tutorial tests to work with the new etch cheatcode behavior.
- Changed the address to 11th. I'm uncertain if this is the ideal approach, so feedback on this particular change would be greatly appreciated.
This should ensure that the NFT tutorial is now up-to-date and functions as expected with the latest changes in the foundry-rs repository.
Please review the changes and provide insights, especially regarding the address change to the 11th. Let me know if …

fix(tutorial): Fixed example tests in NFT tutorial

---

src/cheatcodes/parse-json-keys.md

I have introduced incorrect example of cheatcode usage in #976, this PR fixes it

Fix example for `parseJsonKeys`

---

src/reference/cast/cast-call.md

Downstream of https://github.com/foundry-rs/foundry/pull/5477

feat: add trace docs

---

src/reference/forge/forge-script.md

Downstream of https://github.com/foundry-rs/foundry/pull/5585

feat: add priority gas price docs

---

src/getting-started/installation.md

As we split the cli crate, we need to update this
https://github.com/foundry-rs/foundry/issues/5659#issuecomment-1684237995

fix: add correct cargo command on installation guide

---

src/cast/README.md

`cast --from-utf8` -> `cast from-utf8` 
Cast subcommand doesn't execute properly as shown due to outdated syntax

Cast subcommand syntax in README.md

---

src/reference/forge-std/console-log.md

This import path was incorrect and caused my build to fail. Path was `forge-std/src/console.sol` which failed with error:
```
% forge build
[⠊] Compiling...
Error: 
Failed to resolve file: "/Users/user/Documents/Projects/fluidity-contracts/lib/forge-std/src/src/console.sol": No such file or directory (os error 2).
Check configured remappings..
--> "/Users/user/Documents/Projects/fluidity-contracts/contracts/liquidity/userModule/main.sol"
"forge-std/src/console.sol"
```
The correct path was found here on this page of the book: https://book.getfoundry.sh/reference/forge-std/

Fix import path error, improve readability

---

src/cheatcodes/README.md
src/cheatcodes/fs.md

Add docs for new filesystem cheatcodes `exists`, `isFile` and `isDir` from foundry-rs/foundry#5719
* Update `src/cheatcodes/fs.md` with cheatcode sigs
* Update `src/cheatcodes/README.md` with cheatcode sigs

feat(`cheatcodes`): add docs for exists, isFile and isDir cheats

---

src/cheatcodes/parse-json.md

I was hitting into the same issue described in [issue #179](https://github.com/foundry-rs/forge-std/issues/179) and just found it through Google searching the error.
Just a minor suggestion to add the solution directly to the docs page

Update parse-json.md to reference `foundry.toml` permissions

---

src/cheatcodes/serialize-json.md

Documents new serializeJson cheatcode: https://github.com/foundry-rs/foundry/pull/5755

docs(cheatcodes): add docs for serializeJson

---

src/config/shell-autocompletion.md

Revised the installation process for completion scripts for Forge, Cast, and Anvil commands to ensure proper permissions and prevent `permission denied` errors. Instead of direct file redirection with `>`, I used `sudo tee` to write the output to the respective completion script files in `/usr/local/share/zsh/site-functions/`. This change ensures that the completion scripts are installed with superuser privileges, allowing them to function correctly in the Zsh shell.

Enhanced completion script installation with 'sudo tee'

---

book.toml

Creating PR for this issue: [Issue #1008 ](https://github.com/foundry-rs/book/issues/1008)
The left-hand panel will look cleaner IMO with numerical listing.

Removing no-section-label value from book.toml

---

src/tutorials/best-practices.md

In https://github.com/foundry-rs/book/pull/1004, a section on private key management was added to the best practices page. I think it's a bit too opinionated for the best practices page, so I updated it to be more balanced. 
In general, we should be careful about updating that page—it was originally a collaboration between a few teams to reach best practices we could all agree on, so we should maintain the same level of scrutiny any time that page is changed. Some things are objectively valuable and should always be followed—such as testing scripts—so we can state what to do there confidently and prescriptively. Other things are more subjective and everyone has their own approaches—such as key management—so we should be less prescriptive there and convey the nuances/tradeoffs of various …

Update best practices around private keys

---

src/reference/common/wallet-options-keystore.md

There was a small typo in the `cast send` docs: "--acount" instead of "--account"

Fix "acount" typo in wallet-options-keystore.md

---

src/reference/cast/cast-call.md

The book had a wrong description for the `--trace` flag

[fix] typo in `cast call --trace`

---

src/cheatcodes/parse-json.md

Added short blurbs on Rust's BTreeMap crate ordering system, specifying the caveat that Solidity structs must be declared alphabetically *except that uppercase and lowercase strings are treated differently where uppercase characters precede lowercase ones.
This should add clarity for developers using Foundry's nifty json parsing functionality :)

Document BTreeMap lexicographical order

---

src/cheatcodes/README.md
src/cheatcodes/deal.md

Noted that the `deal` function in the cheatcodes interface allows for modifying ERC-20 token balances. However, based on the current implementation of forge-std, this function isn't directly provided by the VM (which can only change native token balances like ETH). Instead, it's implemented in StdCheats.sol and utilized not through VM calls but directly in test (with support for various ERC standard tokens already added).
This clarification is provided to address potential confusion, which I encountered.

removed alternative `deal` function within the Cheatcodes interface

---

src/cheatcodes/README.md

I noticed that this function selector was missing in the cheatcode reference. I don't know if this is the correct file to edit tho.
Thanks

Add `startBroadcast(uint256 privateKey)` to the cheatcode reference

---

src/reference/cast/cast-create2.md

:memo: cast create2

---

src/reference/cast/cast-create2.md

The `--jobs` argument was added in https://github.com/foundry-rs/foundry/pull/6212 .
`cast create2` help:
```
❯ cast create2 -h
Generate a deterministic contract address using CREATE2
Usage: cast create2 [OPTIONS]
Options:
-s, --starts-with <HEX>      Prefix for the contract address
-e, --ends-with <HEX>        Suffix for the contract address
-m, --matching <HEX>         Sequence that the address has to match
-c, --case-sensitive         Case sensitive matching
-d, --deployer <ADDRESS>     Address of the contract deployer [default: 0x4e59b44847b379578588920ca78fbf26c0b4956c]
-i, --init-code <HEX>        Init code of the contract to be deployed
--init-code-hash <HASH>  Init code hash of the contract to be deployed
-j, --jobs <JOBS>            Number of threads to use. Defaults to and caps …
```

Added `--jobs` to `cast create2`

---

src/reference/cast/cast-create2.md

PR in the main repo got merged https://github.com/foundry-rs/foundry/pull/6363
The `--caller` flag will be added in the next nightly release, so I also added it here to the book.
```
Generate a deterministic contract address using CREATE2
Usage: cast create2 [OPTIONS]
Options:
-s, --starts-with <HEX>      Prefix for the contract address
-e, --ends-with <HEX>        Suffix for the contract address
-m, --matching <HEX>         Sequence that the address has to match
-c, --case-sensitive         Case sensitive matching
-d, --deployer <ADDRESS>     Address of the contract deployer [default: 0x4e59b44847b379578588920ca78fbf26c0b4956c]
-i, --init-code <HEX>        Init code of the contract to be deployed
--init-code-hash <HASH>  Init code hash of the contract to be deployed
-j, --jobs <JOBS> …
```

Added `--caller` for `cast create2`

---

src/config/hardhat.md

fixes #1033 
Was assigned this issue by @Evalir .
The updated tutorial will show folks how to create a combined Foundry + Hardhat project using the latest Hardhat-foundry plugin.
Included both scenarios:
1.  Adding Hardhat to a Foundry project
2.  Adding Foundry to a Hardhat project
Also linked a basic template in the article, I am open to transferring the ownership if you want. My basic template in turn links to [https://github.com/pcaversaccio/hardhat-project-template-ts](https://github.com/pcaversaccio/hardhat-project-template-ts) for anyone who wants a more in-depth template.
Tried to maintain as much resemblance to the OG article as possible.

Rewrote Integrating with Hardhat tutorial

---

src/SUMMARY.md

The getLabel cheatcode page is not working (error 404), adding the link in Summary fixes it
https://book.getfoundry.sh/cheatcodes/get-label.html

Add missing link for page getLabel

---

src/cheatcodes/external.md

Not sure if this was intended, but saw a misplaced `Files` reference link in [Cheatcodes Reference/External ](https://book.getfoundry.sh/cheatcodes/external)(See Screenshot Below)

docs: removed Files link in cheatcode ref/external

---

src/cheatcodes/mock-call.md

While the `mockCall` cheat code in Foundry is advertised to support mocking of functions, it can be overloaded to mock a public variable's getter function. For example, the below code works to mock a public variable called "number":
```
vm.mockCall(
address(example),
abi.encodeWithSelector(bytes4(keccak256("number()"))),
abi.encode(5)
);
```
This is useful when testing interactions with vendored contracts or precompiles, in which case the developer may not have control over a public variable otherwise.

Add mocking of public variables to book

---

src/reference/forge/forge-script.md

flag was missing in the script documentation, but is a valid flag. copied description from the build documentation

add `--skip` flag in forge script documentation

---

src/reference/cast/cast-send.md

Even though there is technically an example of how to add hex data to the `input` field of the transaction object [here](https://book.getfoundry.sh/cast/), it took me a long time to find this. This PR adds an example of how to do this directly on the `cast-send` page.

docs: add example to /reference/cast/cast-send

---

src/reference/config/project.md

Adds the `script` variable to the project config options for `foundry.toml`.
Closes #1082

Add `script` val to config options

---

src/tutorials/best-practices.md

As https://github.com/foundry-rs/foundry/issues/3396 got merged, there is no need to sort imports manually anymore so removing these 2 points from the best practices list.

Best practices: no need to sort imports manually anymore

---

src/cheatcodes/stop-and-return-state-diff.md

The enum `AccountAccessKind` is currently out of sync with the enum in foundry: https://github.com/foundry-rs/forge-std/blob/36c303b7ffdd842d06b1ec2744c9b9b5fb3083f3/src/Vm.sol#L26-L49

Fix: update AccountAccessKind

---

src/cheatcodes/expect-revert.md

According to the documentation regarding the unexpected behaviour of `vm.expectRevert()` on low level calls, the return data is clobbered, and according to my tests it does not seem like the `bytes` argument matters at all, ie. I can remove it, or include something nonsensical, and it doesn't affect the outcome of the test.
Therefore the docs should not suggest providing this argument.

Remove unused error message argument in example code

---

scripts/gen_output/help.py

https://github.com/foundry-rs/foundry/pull/6866

fix: allow empty command descriptions

---

src/reference/cast/cast-call.md
src/reference/cli/cast/call.md

This updates the docs to reflect that the `--verbose` flag was removed from `call`.
See:
https://github.com/foundry-rs/foundry/pull/6939
https://github.com/foundry-rs/foundry/pull/6219

cast: update `call` flags

---

src/cheatcodes/expect-revert.md

This reverts commit dbefc9af30ebd288fbf1ef5dd4e568113196c8ad (from https://github.com/foundry-rs/book/pull/1091)
Discussed with @Evalir in discord and this should work as expected, cc @maurelian

Revert "Remove unused error message argument in example code (#1091)"

---

src/tutorials/forking-mainnet-with-cast-anvil.md

Current example doesn't work with 0.2.0 version. Adding switch `unlocked` fixes this.
Specifically it throws error:
```
Error accessing local wallet. Did you set a private key, mnemonic or keystore?
Run `cast send --help` or `forge create --help` and use the corresponding CLI
flag to set your key via:
--private-key, --mnemonic-path, --aws, --interactive, --trezor or --ledger.
Alternatively, if you're using a local node with unlocked accounts,
use the --unlocked flag and either set the `ETH_FROM` environment variable to the address
of the unlocked account you want to use, or provide the --from flag with the address directly.
```

Impersonation doc fix

---

src/reference/config/solidity-compiler.md

Documented about the "new ignored_warnings_from config setting", wrote it with an example under the Solidity Compiler section and under general section of the Solidity compiler configuration.  I wrote it just above "ignored_error_code" section, attached a screenshot as well. I've run it  and tested the doc page.

Docnewignwarning

---

src/tutorials/solidity-scripting.md

Updates Solidity Scripting Tutorial code example so that it complies with OpenZeppelin dependency.
The function signature of the OpenZeppelin Ownable class has changed in v5 from v4, the constructor now requires an "initialOwner" parameter, which has now been included and uses `msg.sender` as the argument. This change also sets a ref pointing to a release tag for the OpenZeppelin library in the `forge install` command so that it does not default to retrieving the master branch and won't pull in backwards incompatible changes in future. 
Fixes foundry-rs/book#1119.

Update Solidity Scripting Tutorial

---

src/cheatcodes/README.md
src/cheatcodes/expect-call.md

`where` is called `callee` now:
https://github.com/foundry-rs/forge-std/blob/1d0766bc5d814f117c7b1e643828f7d85024fb51/src/Vm.sol#L1059-L1075

docs: update param in "expectCall"

---

src/tutorials/forking-mainnet-with-cast-anvil.md

The address used for the "LUCKY_USER" environment variable is different from the address retrieved from Etherscan although they should be the same. I kept the second one because it holds DAI whereas the first one don't.
Also, it makes more sense to name this user "unlucky" instead of "lucky" because we are basically stealing funds from him/her. It can be confusing for anyone reading the tutorial, as it was confusing for me at first.

Small fixes to the "Forking Mainnet" tutorial

---

src/reference/cast/cast-balance.md

feat: example for cast balance --erc20

---

src/misc/struct-encoding.md
src/reference/cast/cast-balance.md

Nested Struct encoding example

---

src/config/shell-autocompletion.md

Neither all ARM machines run macOS nor all macOS machines are ARM-based.

"macOS" instead of "ARM" for homebrew

---

src/reference/config/solidity-compiler.md

It seems to me that the default evm_version is actually paris, and not london.
https://github.com/foundry-rs/foundry/blob/ce22450e4d625d12ff88fae347a68e3d3d9d2b61/crates/config/src/lib.rs#L1856

fix default evm version (london=>paris)

---

.github/workflows/test.yml
.github/workflows/update.yml

This PR adds a weekly automated update workflow to more regularly update the command output in the documentation as command flags are added quite regularly in Foundry. You can also trigger this workflow manually.
The automated PR looks like this: https://github.com/zerosnacks/book/pull/3

Add weekly automated command output update workflow 

---

.github/workflows/update.yml

Recently the automated `update` workflow was added in https://github.com/foundry-rs/book/pull/1135
The first workflow run unfortunately failed due to a failing test here: https://github.com/foundry-rs/book/actions/runs/8218147817 because of the recently added https://github.com/foundry-rs/book/pull/1136 which fails because of outdated `forge-std`.
This PR updates the `forge-std` git submodule and makes sure the `update` workflow checks out the submodules recursively (alternative is `non-recursive`, slightly less future proof).
Workflow run looks like this: https://github.com/zerosnacks/book/pull/4

Fix failing automated workflow post #1136

---

src/SUMMARY.md
src/cheatcodes/external.md
src/cheatcodes/prompt.md
src/reference/config/testing.md

Following https://github.com/foundry-rs/foundry/pull/7012.
Adds a section that documents the `vm.prompt` and `vm.promptSecret` cheatcodes, including best practices (as described in the Foundry PR) and examples for common use cases.
Also added the `prompt_timeout` config to the configuration reference page.

Document `vm.prompt` cheatcodes

---

src/tutorials/testing-eip712.md

method `_mint()` and `_burn()` in MockERC20 are `internal`. Before use it, we need to extends MockERC20, just like [MockERC20.t.sol](https://github.com/foundry-rs/forge-std/blob/master/test/mocks/MockERC20.t.sol)

fix:need to extend MockERC20,before use it

---

src/cheatcodes/mock-call-revert.md

`mockCallRevert(address, input, error)` makes a call revert with the bytestring from `error`.
The documentation example expects the mock that reverts with `abi.encode(error)` to return `error`, but abi-encoding a string makes the bytestrings not match anymore and the test to fail with a confusing error `REVERT_MESSAGE != REVERT_MESSAGE`.
This PR removes the unnecessary `abi.encode` wrapper.
Try out the examples. Create a new Foundry project with `foundry init` and replace the default test with the following file:
<details><summary>MockCallRevert.t.sol</summary>
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;
import {Test, console} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";
contract MockRevertTest is Test {
function …
```

Fix revert message type in mockCallRevert example

---

src/reference/forge/forge-inspect.md

`forge inspect` is missing `errors` and `events` fields

Update forge inspect with errors and events fields

---

src/cheatcodes/get-code.md
src/cheatcodes/get-deployed-code.md

Updates `getCode` and `getDeployedCode` doc with artifact path formats supported. Ref https://github.com/foundry-rs/foundry/pull/7597#issuecomment-2042695764

Update `getCode` doc

---

src/tutorials/create2-tutorial.md

A small change: re-positioned the info box ('This guide is intended to help understand `CREATE2`. [...]) from the bottom of the page to the top. It is now positioned just after the introductory paragraph. 
Reason: the reader needs this information before reading through the page, not after.  
Hope that makes sense & thanks to for all for the work on Foundry book. It's an amazing resource.

Repositioned info box at page 'Deterministic deployment using CREATE2'  from bottom to top.

---

src/forge/deploying.md

New Foundry users coming to the documentation wanting to find tutorials on deploying and verifying will always go to the "Deploying and Verifying" section of the doc because it's one of the top sections and sits at a more conspicuous location , but it only mentions the CLI approach. This would mislead the new devs to believe that there's no other way to deploy/verify multiple smart contracts using foundry. By mentioning the Solidity Scripting approach, the documentation will better inform the devs with the multiple approaches available to them
(I personally have been believing that Foundry's deployment CLI is the only way to deploy smart contracts with foundry and have been using a hybrid of hardhat + foundry as my setup...because its just impractical to use the CLI for deploying …

mention solidity scripting as an alternative approach to deploying/verifying

---

src/reference/anvil/README.md

it's hard to understand how to influence the finalization of blocks. this adds some visbility if developers search for `finalize` in the book

add `--slots-in-an-epoch` to anvil reference

---

src/cheatcodes/get-nonce.md

Current code (incorrect):
`uint256 nonce = vm.getNonce(nonce);`
Updated code:
`uint256 nonce = vm.getNonce(alice);`

fix: pass correct value to `getNonce`

---

src/reference/config/solidity-compiler.md

This is related to https://github.com/foundry-rs/foundry/issues/5175:
When the flags like `constant_optimizer` are used as currently documented, then they have no effect.
Furthermore, it seems `use_literal_content` was not documented.

Minor Solidity Compiler Flag Updates

---

src/misc/precompile-registry.md

This pull request updates the Precompile Registry in the Foundry Book to include the PointEvaluation precompile (address 0x0a) introduced in the Dencun upgrade as part of EIP-4844.
As this is a minor addition and correction, it is being submitted directly as a pull request without an associated issue.

Add PointEvaluation precompile (0x0a) to the Precompile Registry

---

src/cheatcodes/stop-and-return-state-diff.md

This pull request updates the AccountAccess struct description in the `vm.stopAndReturnStateDiff()` function documentation to include the recently added `depth` field.
As this is a minor addition to the documentation, it is being submitted directly as a pull request without an associated issue.

Add `depth` field to AccountAccess in stopAndReturnStateDiff docs

---

src/cheatcodes/parse-json.md
src/cheatcodes/parse-toml.md

From conversations it became clear that the current documentation of TOML and JSON misses a practical example of decoding complex nested structs. This addition aims to address this concern.

Fix: clarify how to decode nested structs + abi.decode for TOML and JSON

---

src/cheatcodes/prompt.md

Following https://github.com/foundry-rs/foundry/pull/8082, this PR adds documentation for the `promptSecretUint` cheatcode.

Update prompt docs for `promptSecretUint`

---

src/projects/dependencies.md

When trying to write a `remappings.txt` file for a project I was working on, I encountered a lot of `File not found` errors when running `foundry build`. Following the example in the docs that I intend to edit led me to believe that each remapping in my `remappings.txt` file should not begin with a '@' symbol. Only after trying to build my contracts with that symbol at the start of my remapping lines did `forge` manage to follow the remappings and find the files I intended it to find.
I was using `forge 0.2.0` on WSL (Windows subsystem for Linux).
I would like to spare future developers this headache when they start learning Foundry.

Fix confusing error in remappings docs.

---

src/forge/invariant-testing.md
src/reference/config/testing.md

- clarify that `invariant_` functions are checked by different EVM executors (in order to address https://x.com/0xalpharush/status/1803518242067013820 and explain how could be structured to test all of them at same time) 
- add show progress and threads to general testing profile section

Clarify how invariants are tested, update general testing section

---

src/faq.md

For context see: https://github.com/foundry-rs/foundry/issues/6925

fix: update notice of ~/.svm/ directory usage in regards to changes in `svm-rs`

---

src/faq.md

Follow up of https://github.com/foundry-rs/book/pull/1239
Aims to address: https://github.com/foundry-rs/foundry/issues/6925#issuecomment-2013497221

Followup #1239: add specific pointer for MacOS in regards to default $XDG_DATA_HOME location

---

src/forge/traces.md

Document non-obvious traces that user might face regularly.
Related to https://github.com/foundry-rs/foundry/issues/7463

docs(`forge`): document non-obvious traces

---

src/projects/soldeer.md

Make openzeppelin version consistent to avoid confusion

fix: typo in openzeppelin version

---

src/projects/soldeer.md

Added the following line to the `toml` block for `Updating Dependencies`
```bash
libs = ["dependencies"] # <= This is important to be added
```
Closes #1252

Missing dependencies section in Soldeer

---

src/reference/config/inline-test-config.md
src/reference/config/testing.md

updated docs related to https://github.com/foundry-rs/foundry/pull/8387

add fuzz show_log docs

---

src/cheatcodes/parse-json-keys.md

This solves https://github.com/foundry-rs/foundry/issues/8672
```solidity
string memory json = '{"root_key": [{"a": 1, "b": 2}]}';
string[] memory keys = vm.parseJsonKeys(json, ".root_key.0"); // ["a", "b"] 
```
```solidity
string memory json = '{"root_key": [{"a": 1, "b": 2}]}';
string[] memory keys = vm.parseJsonKeys(json, ".root_key[0]"); // ["a", "b"] 
```

Updated docs(`cheatcodes`): `vm.parseJsonKeys` behaviour is documented incorrectly mentioning

---

src/reference/cast/cast-send.md

closes #1272 
For now sets `cast az` as `to`, should be possible to make cleaner after https://github.com/foundry-rs/foundry/pull/8791

feat: EIP-7702 examples

---

src/getting-started/installation.md

1. **Improved clarity**: 
- Simplified sentence structures to make the content more concise and easier to read.
- Replaced phrases like "If you face any issues" with "If you encounter any issues" for more formal and professional language.
2. **Grammar corrections**:
- Corrected small grammatical issues, such as replacing “then simply follow” with “simply follow,” ensuring consistent tone throughout.
3. **Enhanced flow and consistency**:
- Reorganized some sentences to improve the overall flow of the document, especially in the "Using Foundryup" and "Building from Source" sections.
- Standardized the formatting for technical instructions and commands to maintain consistency across the document.
4. **Better emphasis and formatting**:
- Improved the formatting of the "Note" sections, …

Improve grammar clarity

---

src/reference/anvil/README.md

When running `anvil help` we see this option:
But it is not referenced in the docs.
https://book.getfoundry.sh/reference/anvil/#evm-options
Also, it might be nice to maybe re order the reference page so it matches the help menu of anvil (same categories, order etc.). If ok for you I can send another PR. 
But at least this option will now be in the doc and I believe it is an important one :)
(running `anvil 0.2.0 (f2518c9 2024-08-06T00:19:05.446984000Z)`)

Add missing --fork-transaction-hash for anvil

---

src/output/deps/tree

Closes: https://github.com/foundry-rs/book/issues/1149
The output isn't fully accurate now but good enough to get the point across

fix: incompatible `-L` flag in `tree lib -L 1` on Windows

---

projects/cheatcodes/test/BlastMock.t.sol
projects/cheatcodes/test/EmitContract.t.sol
projects/cheatcodes/test/OwnerUpOnly.t.sol
projects/fuzz_testing/test/Safe.t.sol
projects/fuzz_testing/test/Safe.t.sol.1
projects/fuzz_testing/test/Safe.t.sol.2
projects/fuzz_testing/test/Safe.t.sol.3
projects/test_filters/test/ComplicatedContract.t.sol
projects/test_filters/test/ContractB.t.sol
projects/writing_tests/test/Basic.t.sol
projects/writing_tests/test/Basic2.t.sol
src/cheatcodes/parse-json.md
src/cheatcodes/parse-toml.md
src/config/vscode.md
src/faq.md
src/forge/differential-ffi-testing.md
src/forge/forge-std.md
src/projects/dependencies.md
src/reference/config/solidity-compiler.md
src/reference/ds-test.md
src/reference/forge-std/README.md
src/reference/forge-std/console-log.md
src/tutorials/create2-tutorial.md
src/tutorials/solidity-scripting.md
src/tutorials/solmate-nft.md

Per: https://book.getfoundry.sh/tutorials/best-practices#general-contract-guidance
Closes: https://github.com/foundry-rs/book/issues/1150

chore: prefer named imports over default imports

---

src/reference/config/solidity-compiler.md

documented the 'ignored_warning_from' section in references of solidity-compiler doc
Closes: https://github.com/foundry-rs/book/issues/1114

Fix: document `ignored_warnings_from` setting

---

src/getting-started/first-steps.md
src/getting-started/installation.md

1. **Clarified instructions**:
- Improved the wording and flow of the section, particularly around the creation, "compiling," and testing of a new project with `forge`.
- Ensured that the steps are more straightforward and easy to follow for beginners.
2. **Preserved quoted terms**:
- As per the original intention, kept certain terms like "compile" in quotes to emphasize their technical or specialized meaning in the context.
3. **Maintained consistency**:
- Used consistent phrasing and formatting throughout the text to match the style of the rest of the documentation.
4. **Adjusted tone for clarity**:
- Ensured the tone remains professional and suitable for technical documentation while improving readability and flow.
These changes aim to make the documentation more accessible to new …

Improve grammar clarity First Steps with Foundry

---

src/reference/cast/cast-logs.md

According to my understanding and verification, 
`cast logs --from-block 15537393 --to-block latest 'Transfer (address indexed from, address indexed to, uint256 value)' 0x2e8ABfE042886E4938201101A63730D04F160A82` 
has the same effect as 
`cast logs --from-block 15537393 --to-block latest 'Transfer (address indexed from, address indexed to, uint256 value)'`. 
Therefore, the address in the original example does not take effect. The `--address` option should be added if this is the original intention of the example.

Fix: Correct errors in cast logs example

---

src/getting-started/installation.md

On Windows, the modified installation command worked.

cargo installation command throws an error for 'cast'

---

src/tutorials/solidity-scripting.md

This PR updates the setup instructions to remove the `Counter.s.sol` script file along with other Counter-related files. This change resolves a `forge build` error caused by the presence of the unused Counter script.
Changes made:
- Updated the shell command to remove `script/Counter.s.sol`
- This ensures a clean project setup for the NFT tutorial

Fix: Remove Counter.s.sol to resolve forge build error

---

src/SUMMARY.md
src/cheatcodes/README.md
src/cheatcodes/environment.md
src/cheatcodes/mock-calls.md

Documentation for `vm.mockCalls`, see https://github.com/foundry-rs/foundry/pull/9024.

Document `vm.mockCalls`

---

src/forge/writing-tests.md

This test will not compile if a user follows the docs as written (Error (7576): Undeclared Identifier)  . After adding the stdError import they will be able to run the test successfully.

docs: Update writing-tests.md

---

src/tutorials/solidity-scripting.md

This PR adds a new "Scripting with Arguments" section to the Solidity Scripting documentation. It includes:
- An example of a modified `NFT.s.sol` script that accepts arguments
- A command-line example for running the script with arguments
- Explanation of the new command structure
This addition demonstrates how to create more flexible and reusable Foundry scripts, allowing developers to deploy different NFT contracts without modifying the script each time.

Add "Scripting with Arguments" section to Solidity Scripting documentation

---

src/reference/config/solidity-compiler.md

We now use '"cancun": https://github.com/foundry-rs/foundry/pull/9131 as default

chore: update default `evm_version` to `cancun`, add explainer for pinning

---

src/ci-cd/github-actions.md
src/config/continuous-integration.md
src/getting-started/installation.md

Related: https://github.com/foundry-rs/foundry-toolchain/pull/60
For our stable release, update the Foundry toolchain documentation in the book to point to the latest stable version by default.

chore: start defaulting to stable

---

CONTRIBUTING.md
src/SUMMARY.md
src/anvil/README.md
src/cast/README.md
src/chisel/README.md
src/forge/README.md

Preparation for https://github.com/foundry-rs/foundry/pull/9540
Expand documentation of overview section, the Foundry README will link directly to the detailed references

chore: improve documentation of individual binaries

---

src/README.md
src/SUMMARY.md
src/announcements.md

Adds announcement page with instructions to update to the latest version of `foundryup`, linking to it from the book index

chore: add announcements page

---

src/announcements.md

Update in `foundryup` to use `-V` instead of `--version` to get short version
Related: https://github.com/foundry-rs/foundry/pull/9728

chore: bump version of `foundryup`

---

src/reference/cast/cast-wallet-sign.md

Add a snippet documenting the `cast wallet sign` default behavior using EIP-191 in case readers want to know how to sign unprefixed messages using `--no-hash`

Document cast wallet sign default behavior: EIP-191

---

src/reference/config/solidity-compiler.md

Easy to forget having to set your `evm_version`, this note should help

chore: add note on setting `evm_version` if you are experimenting with future hardfork content (e.g. `EIP-7702`)

---

src/cheatcodes/expect-revert.md

Highlight selective disabling using inline configuration
Add example of error users will likely encounter for searchability
Add explicit example of incorrect use

fix: improve `vm.expectRevert` docs 

---

src/announcements.md

So users not on Twitter / Farcaster also see it

chore: add note on `vm.expectRevert` to announcements page

---

.github/workflows/update.yml

Prevents the undo-ing of breaking changes that are not yet in stable but need to be documented e.g. https://github.com/foundry-rs/book/pull/1418
This is in lieu of setting up two or three different versions of the book, the release candidate version seems to be appropriate to use here

fix: use release candidate version for update workflow

---

scripts/gen_output/forge.sh

Related: https://github.com/foundry-rs/book/pull/1420
No content related changes, required for re-running update workflow resulting from https://github.com/foundry-rs/book/pull/1419

fix: remove unused and deprecated `testFail*` tests for update workflow to pass

---

src/reference/config/solidity-compiler.md

The link in [extra_output](https://book.getfoundry.sh/reference/config/solidity-compiler#extra_output) is invalid and it doesn't help finding anything in the Solidity docs.
I've changed the link to the correct place and included a remark to help people find the available options.

fix: add valid link in solidity compiler extra_output reference

---

src/reference/cast/cast-send.md
src/reference/cast/cast-wallet-sign-auth.md

Closes: https://github.com/foundry-rs/book/issues/1440
Looks like the references have gotten a bit incomplete, will look into how we can more easily automate this.
Added the note on nonce management when using `sign-auth` when intending to send with the same signer

chore: document `cast send --auth` and `cast wallet sign-auth` (EIP-7702)

---

src/cheatcodes/gas-snapshots.md

Documents the new `gas_snapshot_emit` option
Related PR: https://github.com/foundry-rs/foundry/pull/9710

chore: document new way of disabling the emittance of gas snapshots to disk

---

src/cheatcodes/get-code.md

In `get-code.md`, the `See Also` points to the hyperlink `eth` instead of `etch`.

fix(typo): `vm.eth` -> `vm.etch`

---

src/guides/v1.0-migration.md
src/reference/config/solidity-compiler.md

- add additional compilers docs
- update v1.0 migration guide to point to missing `optimizer` and additional compilers usage
- update v1.0 migration guide to warn re usage of new console.log with older signatures / need to update forge-std

Additional compilers docs

---

.github/workflows/update.yml

Required for getting the latest references / updates
Related: https://github.com/foundry-rs/book/issues/1446
Related failure: https://github.com/foundry-rs/book/actions/runs/13457286809

fix: unpin from `rc`, pin to `nightly` in `update` workflow

---

src/cheatcodes/gas-snapshots.md

As a placeholder pending this implementation: https://github.com/foundry-rs/foundry/issues/9912

chore: add note on gas snapshots being inaccurate outside of isolated test mode

---

src/cheatcodes/sign-delegation.md

Updates `cheatcodes/sign-delegation.md` to match the behavior of [EIP-7702](https://eips.ethereum.org/EIPS/eip-7702).
The current description states EOA delegation via EIP-7702 is temporary and only lasts throughout the transaction:
> EIP-7702 sets the account code of an Externally Owned Account (EOA) temporarily during a transaction. This enables EOAs to behave like smart contracts for the duration of a transaction without permanently modifying their code.
I believe this was based on earlier versions of the EIP and is no longer true.

Update EIP-7702 behavior for `sign-delegation` cheatcode

---

src/forge/debugger.md

Related: https://github.com/foundry-rs/foundry/issues/10079
This doc was previously written for the standalone `debug` command, now that it is rolled into `forge test` and `forge script` the default of `<PATH>` is not very helpful in the context of function debugging. Update the doc to point the user to use `--match-test` to select a single function instead.

fix(`debugger`): incorrect docs after removal of `forge debug`

---

src/cheatcodes/expect-emit.md
src/cheatcodes/get-block-timestamp.md

expectEmit.md
Fixed: "Assert" → "Asserts that" (grammar fix, correct verb form).
get-block-timestamp.md
Fixed: "on every forge test" → "in every forge test" (correct preposition ).

Grammar Fixes

---

src/cheatcodes/fs.md

Be me. Spend 30 minutes trying to figure out why I couldn't get permissions to write a csv file, when I had copied the config name out of the docs. It's `fs_permissions` not, `fs_permission`.
Fix the docs, for those who follow after.

It's `fs_permissions` not, `fs_permission`

---

src/reference/anvil/README.md

The no-request-size-limit is very useful when dumping and loading large anvil state. A state dump from replaying all transactions from block 24363415 on top of the previous block is about 5MB which causes anvil to reject loading the state. Had to dig through the source code to find this so it might be helpful to other people who come across a similar issue

Update README.md to include no-request-size-limit flag

---

src/reference/anvil/README.md

Add `--fork-chain-id` documentation to the book. Not sure why it shows up in the help page but not in the book itself so added it manually

Update README.md to include --fork-chain-id

---

src/forge/debugger.md

Debugger can be run on already executed transactions. Adding missing info.

debugger - added cast run info and example

---

projects/cheatcodes/foundry.toml

Old:
https://github.com/gakonst/foundry/tree/master/config
New:
https://github.com/foundry-rs/foundry/tree/master/crates/config
Reason for the change:
The original link pointed to gakonst/foundry, which is outdated or deprecated.
The new link redirects users to the canonical and actively maintained foundry-rs repository, improving accuracy and consistency in documentation.

Update config link in foundry.toml to point to official repository

---

src/reference/forge/forge-clone.md
src/reference/forge/forge-init.md
src/reference/forge/forge-install.md

Forge v1.1.0 with https://github.com/foundry-rs/foundry/pull/9884 removed the option for `--no-commit` and added an option for `--commit`
This PR updates the corresponding pages according to the new behavior.

Remove `--no-commit`, add `--commit`

---

src/announcements.md

Adds `1.1 (stable)` and `1.2 (rc)` to releases

chore: update release notes on announcement page

---

vocs/docs/pages/forge/deploying.md
vocs/docs/pages/forge/reference/forge-create.mdx

This pull request corrects the documentation for the `forge create` command to reflect the correct argument order, addressing an issue where the documented examples would fail.
The `<CONTRACT>` argument must be specified before any other options. This PR updates the command's synopsis, examples, and adds an explicit note to clarify the correct usage.
**Changes:**
*   Updated the `SYNOPSIS` in `forge/reference/forge-create.mdx` to show the correct argument position.
*   Corrected the command example in `forge/deploying.md` to move `--constructor-args` to the end.
*   Added a note to `forge/reference/forge-create.mdx` to explicitly state that the contract path must be provided first.
This resolves the confusion reported and ensures the documentation matches the tool's behavior.
Fixes #1244

`docs: Fix forge create command argument order`

---

vocs/docs/pages/anvil/overview.md

Ref: https://github.com/foundry-rs/foundry/pull/10747#issuecomment-3018127677
The note: 
> EIP-7702 and Default Accounts
> Since the advent of EIP-7702, Anvil's default accounts have been delegated to drainers such as > https://etherscan.io/address/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266#authlist7702
> This can negatively impact developer experience when users are running Anvil in fork mode and are making RPC calls that > involve one of the default anvil accounts. To avoid this issue, use a different mnemonic when starting Anvil:
> ```anvil --mnemonic "<custom mnemonic>" --fork-url https://reth-ethereum.ithaca.xyz/rpc```

docs(`anvil`): note about 7702 and default accounts in fork mode

---

vocs/docs/pages/config/reference/default-config.mdx
vocs/docs/pages/config/reference/testing.mdx
vocs/docs/pages/forge/advanced-testing/invariant-testing.md
vocs/docs/pages/forge/tests/fork-testing.md

- document Invariant time based campaigns and Coverage-Guided Fuzzing mode 
- add time based campaigns `timeout` and `show_solidity` configs for `[invariant]` section
- add `timeout` and `fail_on_revert` configs for `[fuzz]` section
- forking test note re `eth_getAccountInfo` Reth API
- update default value of `gas_limit` config

Update invariant docs + leftovers

---

vocs/docs/pages/guides/deterministic-deployments-using-create2.md
vocs/docs/pages/guides/eip712.md
vocs/docs/pages/guides/forking-mainnet-with-cast-anvil.md
vocs/docs/pages/guides/project-setup/clone-a-verified-contract.mdx
vocs/docs/pages/guides/project-setup/creating-a-new-project.md
vocs/docs/pages/guides/scripting-with-solidity.md

Closes #1607 
Adds steps to procedural guides: https://vocs.dev/docs/kitchen-sink#steps
Added to:
1. https://yash-steps-in-guides.foundry-book.pages.dev/guides/deterministic-deployments-using-create2
2. https://yash-steps-in-guides.foundry-book.pages.dev/guides/forking-mainnet-with-cast-anvil
3. https://yash-steps-in-guides.foundry-book.pages.dev/guides/scripting-with-solidity#deploying-the-counter-contract
4. https://yash-steps-in-guides.foundry-book.pages.dev/guides/project-setup/creating-a-new-project
5. https://yash-steps-in-guides.foundry-book.pages.dev/guides/project-setup/clone-a-verified-contract

feat(`guides`): add steps

---

vocs/docs/public/_redirects

`/cast/reference/cast-:splat /cast/reference/:splat`
`/forge/reference/forge-:splat /forge/reference/:splat`

fix: :splat redirects

---

vocs/docs/pages/benches.mdx
vocs/docs/pages/releases.mdx
vocs/docs/pages/releases/nightly.mdx
vocs/scripts/fetch-benchmarks.ts
vocs/vocs.config.ts

The script would only categorize nightly versions as the latest version in script and not tagged releases.

fix: fetch-benches script to identify latest version

---

vocs/docs/pages/reference/cheatcodes/overview.mdx
vocs/docs/snippets/output/vm/Vm.sol
vocs/sidebar/cmd-reference.ts
vocs/sidebar/sidebar.ts

Cheatcodes reference snippet wasn't rendering.
Fixes that and adds the overview link to the sidebar similar to other sections
Preview: https://yash-fix-cheats-ref.foundry-book.pages.dev/reference/cheatcodes/overview

fix: cheatcodes reference + add overview link in sidebar

---

vocs/docs/pages/forge/advanced-testing/fuzz-testing.md
vocs/docs/pages/forge/advanced-testing/table-testing.md

Relevant to table tests / fuzz test fixtures
Ref: https://x.com/zerosnacks/status/1957825999812403275

chore: clarify naming requirement for parameters w/ fixtures

---

vocs/docs/public/_redirects

https://getfoundry.sh/reference/forge-std redirects now properly but https://getfoundry.sh/reference/forge-std/ which was originally pointed out doesn't. Add redirect for URL with trailing slash

redirect also forge-std url with trailing /

---

vocs/docs/pages/config/hardhat.md

The current documentation suggests installing Hardhat with:
```bash
npm install --save-dev hardhat
```
This now pulls in **Hardhat v3.0.0**, which is not yet supported by `@nomicfoundation/hardhat-foundry` (requires Hardhat `^2.26.0`).
This PR updates the command to explicitly install the latest supported **Hardhat v2.x**:
```bash
npm install --save-dev hardhat@^2.22.0
```
This ensures compatibility with the Hardhat–Foundry integration and prevents dependency resolution errors when following the setup guide.

Fix Hardhat install command to use compatible v2.x

---

.github/workflows/deploy.yml
.github/workflows/test.yml
.github/workflows/update.yml

Updates actions/checkout@v4 to actions/checkout@v5 across CI workflows.
Upgrade to actions/checkout@v5 for improved performance and stability.
Reference:
Latest version: https://github.com/actions/checkout/releases/tag/v5.0.0

Update GitHub Actions in CI Workflows 

---

vocs/docs/pages/introduction/installation.md

Reverts foundry-rs/book#1662
Fixes https://github.com/foundry-rs/book/issues/1663

Revert "docs: use --version instead of --install to install the specific version"
