foundry-rs/book

README.md, src/SUMMARY.md, src/forge/guide/project-layout.md, src/forge/guide/readme.md, src/forge/guides/ds-test-docs.md, src/forge/guides/writing-tests.md, src/getting-started/first-steps.md, src/introduction.md
Gm, ser,
I'm eager to contribute to the book!
Here's what this PR contains:
- New `ds-test` documentation section
- Writing Tests guide
- Miscellaneous contributions (fixes, improvements, callouts, and serial commas)
I'm going to further contribute to the book in the following days.
🌸
=> Add ds-test docs, Writing Tests guide, and misc

src/reference/cheatcodes.md, src/reference/ds-test.md
Your latest additions to the book are great, ser.
I wanted to make some parts more friendly to new users by providing examples.
If you like this PR, note there are a few cheatcodes I do not know how to use properly and have not provided examples for:
- **ffi** *(here, for example, I don't quite understand the  input, and why it is like that)*
- **getCode** *(couldn't get it to work)*
Also included: Minor additions to `ds-test.md`
🌸
=> Add examples to Cheatcodes Reference, and misc

src/SUMMARY.md, src/cast/cast-overview.md, src/cast/index.md, src/forge/cheatcodes.md, src/forge/creating-a-new-project.md, src/index.md, src/reference/cast.md
- Add Cast Guide
- Begin `cast` Reference
- misc fixes
=> Add Cast Guide and begin `cast` Reference

src/cast/cast-overview.md, src/reference/cast.md
- Began writing the `cast` Subcommands section
- Added another example in `cast-overview.md`
=> Nightly PR: Begin writing `cast` Subcommands section, and more

src/cast/cast-overview.md, src/forge/cheatcodes.md, src/forge/config.md, src/forge/writing-tests.md, src/getting-started/first-steps.md, src/index.md, src/reference/cast.md, src/reference/cheatcodes.md, src/reference/ds-test.md
- Just a boring PR (misc fixes)
- Added overviews to the `ds-test` reference
=> Fix miscellaneous

src/SUMMARY.md, src/forge/deploying.md, src/forge/index.md
- How to verify contracts on Etherscan
sorry for the force push
=> Add Verifying

src/forge/deploying.md
A few details I forgot to add last time:
- change wording
- add command outputs
- add `forge verify-check`
=> Add more info to Verifying

src/forge/tests.md
Fixes https://github.com/onbjerg/foundry-book/issues/50
=> feat: docs for --match-path and --no-match-path

src/reference/config.md
#48 
I added some info for `--offline` option.
=> document offline mode

src/reference/cheatcodes.md
#37 
Some basic documentation of the `assume` cheatcode.
=> add assume cheatcode

src/forge/writing-tests.md
Added test deploy address description. As discussed @ https://github.com/onbjerg/foundry-book/issues/43#issue-1147412045
=> Update writing-tests.md with test contract address. 

src/forge/continous-integration.md
=> Fix typo in continous-integration.md

src/reference/cheatcodes.md
Sorry for the confusion in #108!
Thanks @cruzdanilo and @mds1 for the help.
=> expectEmit: topic disambiguation

src/SUMMARY.md
@onbjerg hey sry missed the renaming of the path :)
=> fixing route for tutorial after renaming

src/reference/cheatcodes.md
Fixes https://github.com/onbjerg/foundry-book/issues/110
=> Document expectRevert()

src/reference/cast.md
Adds `cast find-block` to `cast.md`
Closes #56
=> Add cast find block

src/tutorials/solmate-nft.md
realized while reading that /getting-started was a broken link, its a heading not an actual page
=> Broken Link

src/reference/cheatcodes.md
follow up on https://github.com/gakonst/foundry/issues/1124
=> add info on `expectRevert` with low-level calls

src/forge/deploying.md
lmao, i was conflicted between making an issue or a pr but here we are
=> corrected contructor typo

src/forge/cheatcodes.md, src/tutorials/solmate-nft.md
This PR depends on #157 being merged first.
If you decide not to merge #157, I'd be happy to reapply my changes here.
=> Refactor code snippets to use custom errors

book.toml, src/forge/debugger.md, src/static/custom.css
Catches up with all the new things in the debugger
=> docs: catchup with debugger features

src/SUMMARY.md, src/forge/gas-snapshots.md
Add gas-snapshot documentation.
=> Docs: add gas-snapshots

src/SUMMARY.md, src/config/static-analyzers.md
re https://github.com/foundry-rs/book/issues/212
=> add static analyzers to config w slither & mythril

src/tutorials/solmate-nft.md
=> fix: nft tutorial

src/forge/forking-mode.md
Add docs to forking-mode.md for this PR:
https://github.com/foundry-rs/foundry/pull/1349
=> docs: add docs for --etherscan-api-key in forking-mode

src/cheatcodes/README.md, src/cheatcodes/set-nonce.md
`vm.setNonce` docs contain errors.
=> docs: fix `vm.setNonce` info

src/projects/working-on-an-existing-project.md
change directory into the cloned repo
=> add missing command

src/reference/forge/compiler-options.md, src/reference/forge/forge-build.md
=> docs: update `--optimizer-runs`

src/faq.md
add info about local solc installation
=> docs: add info about path to solc binary

src/tutorials/foundry-docker.md
Please see the issue in Foundry for discussion around this topic:
https://github.com/foundry-rs/foundry/issues/1411
=> Add note about missing dev packages in docker image (addresses foundry-rs/foundry #1411)

src/tutorials/solmate-nft.md
=> Update broken link to cheatcodes

src/forge/advanced-testing.md
Updated Advanced Testing to include the Differential Testing text and the link to the file
=> Updated Advanced Testing

src/tutorials/solmate-nft.md
cheatcodes link in the solmate tutorial was still broken
=> fix: update broken link to cheatcodes

src/config/shell-autocompletion.md
=> fix(shell-autocompletion.md): fix docs

.gitignore, src/SUMMARY.md, src/cheatcodes/assume.md, src/reference/forge-std/bound.md, src/reference/forge-std/std-cheats.md
issue: 
https://github.com/foundry-rs/book/issues/267
=> docs: document bound std cheat (forge std)

src/cheatcodes/README.md
added comment matches line here https://github.com/foundry-rs/foundry/blob/b7c0774f3599f800dcf61c7b329761cce611eb57/testdata/cheats/Cheats.sol#L46
=> docs: add 2nd form of expectEmit to cheatcodes reference

src/getting-started/installation.md
1. According to https://github.com/foundry-rs/foundry/pull/1037, current installation command will get error below.
```
error: multiple packages with binaries found: anvil, foundry-cli. When installing a git repository, cargo will always search the entire repo for any Cargo.toml. Please specify which to install.
```
2. provide update command to get the latest version of Foundry.
=> feat(installation.md): feat update to latest command

src/config/static-analyzers.md
Trailing comma in the json arrays isn't valid. Also added the commands to use solc-select
=> Slither/Mythril JSON

src/SUMMARY.md, src/cheatcodes/README.md, src/cheatcodes/coinbase.md, src/cheatcodes/environment.md
issue: https://github.com/foundry-rs/book/issues/285
~~1. will update example~~
2. Put coinbase at bottom of `src/cheatcodes/README.md`
- by following forge-std: https://github.com/foundry-rs/forge-std/blob/5927f70bd40e0967d1e4e2c18f0c982ba9a02957/src/Vm.sol#L71-L72
=> docs: document vm.coinbase

src/reference/forge/forge-inspect.md
https://github.com/foundry-rs/book/issues/294
Didn't realize it was a one liner
=> docs: add forge inspect --pretty flag

src/SUMMARY.md, src/reference/forge/forge-cache-ls.md, src/reference/forge/forge-cache.md, src/reference/forge/forge.md, src/reference/forge/utility-commands.md
issue: https://github.com/foundry-rs/book/issues/296
=> docs: add forge-cache-ls docs

src/SUMMARY.md, src/cheatcodes/start-prank.md, src/reference/forge-std/change-prank.md, src/reference/forge-std/std-cheats.md
https://github.com/foundry-rs/book/issues/304
A bit unsure about description.
=> docs: changePrank std cheat

src/reference/cast/cast-interface.md
issue: https://github.com/foundry-rs/book/issues/300
=> docs: cast interface --name flag

src/reference/config.md
=> fix(config.md): change the scope of evm_version

src/reference/config.md, src/reference/forge/forge-build.md
issue: https://github.com/foundry-rs/book/issues/301
also added the additional optimizer settings because I didn't see it
https://github.com/foundry-rs/foundry/tree/master/config#additional-optimizer-settings
and
https://github.com/foundry-rs/foundry/tree/master/config#additional-model-checker-settings
=> docs: document smt options

src/cheatcodes/expect-call.md, src/cheatcodes/mock-call.md
=> docs: documented mockCall and expectCall with msg.value

src/README.md, src/SUMMARY.md, src/config/hardhat.md
This has been asked a few times in the Telegram group now.
=> docs: add Hardhat integration page

src/reference/forge/forge-bind.md
closes: https://github.com/foundry-rs/book/issues/326
=> docs: add forge bind --skip-cargo-toml

src/reference/forge/forge-create.md
Closes https://github.com/foundry-rs/book/issues/341.
=> docs: add `forge create --nonce`

src/SUMMARY.md, src/reference/forge/forge-upload-selectors.md, src/reference/forge/forge.md, src/reference/forge/utility-commands.md
closes: https://github.com/foundry-rs/book/issues/328
=> docs: add forge-upload-selectors

src/reference/config.md
closes: https://github.com/foundry-rs/book/issues/342
=> docs: add allow_paths in config reference

src/SUMMARY.md, src/reference/cast/abi-commands.md, src/reference/cast/cast-upload-signature.md, src/reference/cast/cast.md
closes: https://github.com/foundry-rs/book/issues/329
Added it under cast - abi commands: https://book.getfoundry.sh/reference/cast/abi-commands.html
=> docs: add cast upload-signature

src/reference/forge/forge-script.md
closes: https://github.com/foundry-rs/book/issues/357
=> docs: add forge script flags etherscan-api-key, json, verify

src/config/hardhat.md
See https://github.com/foundry-rs/hardhat-foundry-template/pull/2#issue-1262035721
=> Fixes bug (assumed imports are done with double quotes)

src/reference/forge/forge-cache-clean.md
=> Add entry to forge-cache-clean for --etherscan

src/SUMMARY.md, src/reference/forge-std/README.md, src/reference/forge-std/assertEq.md, src/reference/forge-std/std-logs.md
=>  Document assertEq for arrays and Std Logs (Forge Std)

src/reference/anvil/README.md
Documented the two new RPC calls and deleted some unnecessary dots in the end of some sentences.
Fix #378
=> Documented new Anvil RPC calls

src/tutorials/solmate-nft.md
found in 
[src/tutorials/solmate-nft.md
](https://github.com/foundry-rs/book/blob/master/src/tutorials/solmate-nft.md)
This tutorial walk you through >> This tutorial will walk you through
=> fixed typo in solmate-nft example

src/reference/forge/core-build-options.md
Added the documentation for --silent flag
=> Add --silent falg documentation for core build options

src/reference/cast/cast-run.md
=> Verbose option for cast run

src/reference/anvil/README.md, src/reference/forge/executor-options.md
closes https://github.com/foundry-rs/book/issues/391
=> add base-fee alias

src/reference/anvil/README.md
update cli arg reference accordingly 
https://github.com/foundry-rs/foundry/pull/2169
=> docs: update anvil cli arguments

src/reference/cast/cast-send.md, src/reference/common/transaction-options.md, src/reference/forge/forge-create.md
Closes https://github.com/foundry-rs/book/issues/412.
=> docs: unify transaction options for `forge create` and `cast send`

src/cheatcodes/ffi.md, src/cheatcodes/to-string.md, src/forge/differential-ffi-testing.md
=> feat: document vm.toString()

src/reference/anvil/README.md
add `ANVIL_IP_ADDR` info from https://github.com/foundry-rs/foundry/pull/2185
=> docs: add anvil ip docker section

src/SUMMARY.md, src/cheatcodes/README.md, src/cheatcodes/environment.md, src/cheatcodes/get-recorded-logs.md, src/cheatcodes/record-logs.md
For context, please refer to https://github.com/foundry-rs/foundry/pull/2161
=> Add documentation for cheatcodes vm.recordLogs() and vm.getRecordedLogs()

src/reference/cast/cast-call.md
Just a little example 
linked to #423
=> docs: new example for cast call

src/projects/dependencies.md, src/reference/forge/forge-install.md
[v7](https://github.com/Rari-Capital/solmate/tree/v7) is the most up-to-date version of Solmate.
=> Bump Solmate version

src/reference/forge/forge.md
=> Fix forge snapshot link

src/reference/forge-std/README.md
After adding this function to the std library I figured I should update the book.
https://github.com/foundry-rs/forge-std/pull/111
=> add computeCreateAddress reference to book

src/reference/config.md
this syncs with the foundry-rs repo the documentation for the adv. configuration for the compiler steps
I also added a resource link to formatting a TOML file
=> docs(toml-config): add adv. config section

src/reference/forge/forge-create.md
=> docs(forge): add create --unlocked flag

src/reference/anvil/README.md
=> docs: update transport layer section

src/reference/forge-std/deployCode.md
Documentation of the two new deployCode signatures which consider values.
Fix #461
=> Documented deployCode signatures with value

src/config/shell-autocompletion.md, src/reference/anvil/README.md
document https://github.com/foundry-rs/foundry/pull/2485
=> feat: document anvil shell completions

src/cheatcodes/rpc.md
Correct the config according to [Config](https://book.getfoundry.sh/reference/config#rpc_endpoints).
=> fix(rpc.md): error config in rpc_endpoints

src/cheatcodes/ffi.md
=> docs: document ffi behaviour

src/reference/forge/forge-bind.md
=> docs: update forge bind

src/SUMMARY.md, src/reference/forge-std/make-addr-and-key.md, src/reference/forge-std/make-addr.md, src/reference/forge-std/std-cheats.md
=> docs: add makeAddr and makeAddrKey

src/reference/forge/forge-script.md
=> Document `--gas-estimate-multiplier` and `--skip-simulation` params for `forge script`

src/reference/anvil/README.md
Cf. https://github.com/foundry-rs/foundry/pull/2717#pullrequestreview-1069642421
=> docs: Add `evm_setBlockGasLimit`

src/reference/anvil/README.md
issue: #514 
related pr: https://github.com/foundry-rs/foundry/pull/2711
=> docs: add anvil's `--timestamp` flag

src/reference/cast/cast-storage.md
https://github.com/foundry-rs/foundry/issues/2738#issuecomment-1213055370
=> mention that slot number should be hex

src/reference/config.md
Update `FormatConfig` options per [source](https://github.com/foundry-rs/foundry/blob/44cd2008351b6b62ddb28d850f629f3073a576b3/config/src/fmt.rs)
=> Update fmt config options

src/config/continous-integration.md
This took a bit of experimentation to get working on my end so I figured it would be useful to provide this information for how to set this up for Travis as well.
=> Add sample travis config

src/forge/fork-testing.md
The code does not compile, I made some modifications so that the beginners can make it compile without too much effort
By replacing "cheats" by "vm" at the right place in the code.
and "string public value;" by "uint256 public value;" in the smart contract SimpleStorageContract.
=> Fix compilation issue in SimpleStorageContract

src/SUMMARY.md, src/cheatcodes/README.md, src/cheatcodes/environment.md
corresponds with https://github.com/foundry-rs/foundry/pull/2814
=> docs: document vm.difficulty

src/config/README.md
Updated the foundry.toml section to now be in line with how this should be written in the lastest version of foundry
=> Nit on foundry.toml profile

src/config/static-analyzers.md
add mythril installation and change mythril doc link
=> add mythril installation and change mythril doc link

src/config/static-analyzers.md
This pull request has 3actions in two commits 
Commit 1 - mythril custom json usage syntax correction & addition of example output for mythril 
Commit 2 - Adding github action which are available for incorporating slither into CI/CD
=> Fix mythril syntax and additions add slither github action link for ci/cd

src/reference/forge/compiler-options.md, src/reference/forge/core-build-options.md, src/reference/forge/executor-options.md, src/reference/forge/forge-script.md, src/reference/forge/watch-options.md
This PR is for punctuation and word changes (minor).
=> Forge Script Markdown Spelling and Punctuation

src/reference/common/etherscan-options.md
for `cast send` `-c` is an alias for `--confirmation` and not `--chain`
=> rm invalid --chain alias

src/reference/anvil/README.md
=> docs: add --init argument

src/forge/fork-testing.md
I'm new to Foundry and when I was learning about fork testing I didn't know how to access my .env variables in my mycontract.t.sol file. I think it's legit to add it there, because most people want to add their tests to version control and work open source. See my requested changes. Open to suggestions.
The section (2x) I'm talking about inside fork-testing documentation.
```Solidity
//Replace ALCHEMY_KEY by your alchemy key or Etherscan key , change RPC url if need
//string MAINNET_RPC_URL = 'https://eth-mainnet.g.alchemy.com//v2/ALCHEMY_KEY';
//string OPTIMISM_RPC_URL = 'https://xxxxxxxx.alchemyapi.io/v2/ALCHEMY_KEY';
// create two _different_ forks during setup
function setUp() public {
mainnetFork = vm.createFork(MAINNET_RPC_URL);
optimismFork = vm.createFork(OPTIMISM_RPC_URL);
}
```
=> Explain how to access .env vars

src/tutorials/solidity-scripting.md
Also remove the test file as it breaks `forge build`
which is the next step in the instructions.
=> Update scripting docs with new default contract name

projects/cheatcodes/foundry.toml, projects/fuzz_testing/foundry.toml, projects/test_filters/foundry.toml, projects/writing_tests/foundry.toml, src/config/README.md, src/config/hardhat.md, src/reference/config/testing.md, src/reference/forge/forge-build.md
- fix profile section names
- add description of standalone sections
- add description of invariant fallback logic
cc @gakonst
=> Add standalone section & invariant fallback description

src/reference/config/overview.md
=> docs: document FOUNDRY_FFI unsuported

src/forge/gas-snapshots.md
I tried out of curiosity if I can filter based on match path and match test when taking snapshot. It makes so much sense to have this feature. As expected it worked. Adding it in the documentation to help a future reader :)
=> Usage of sub commands with the snapshot command

src/reference/config/solidity-compiler.md
=> docs: document auto_detect_remappings

src/SUMMARY.md, src/cheatcodes/README.md, src/cheatcodes/external.md, src/cheatcodes/parse-json.md
=> fix: link parse-json

src/reference/forge/forge-create.md, src/reference/forge/forge-verify-contract.md
Closes https://github.com/foundry-rs/book/issues/588.
=> docs: forge verify-contract --constructor-args

src/tutorials/solidity-scripting.md
=> Fixed typo in bash snippet

src/config/hardhat.md, src/tutorials/foundry-docker.md
=> Fix: typos

src/cheatcodes/broadcast.md, src/cheatcodes/start-broadcast.md
Re https://github.com/foundry-rs/foundry/pull/3111
=> docs: update broadcast and startBroadcast with private key overloads

src/cheatcodes/broadcast.md, src/cheatcodes/start-broadcast.md, src/tutorials/solidity-scripting.md
Includes commits from #598 which should be merged first. 
https://github.com/foundry-rs/foundry/pull/3111 should also be merged first.
=> docs: solidity scripting tutorial using private key broadcast methods

src/forge/deploying.md, src/reference/common/retry-options.md, src/reference/common/verifier-options.md, src/reference/forge/forge-create.md, src/reference/forge/forge-verify-check.md, src/reference/forge/forge-verify-contract.md
=> Update verify params & Add `Known Issues` section to verification

src/cheatcodes/set-env.md
See discussion in https://github.com/foundry-rs/foundry/issues/3107.
=> docs: clarify setEnv cheatcode effect

src/SUMMARY.md, src/reference/cast/cast-rhl.md, src/reference/cast/cast-shl.md, src/reference/cast/cast-shr.md, src/reference/cast/cast.md, src/reference/cast/conversion-commands.md, src/reference/common/shift-options.md
Addings docs for `cast shr / shl` from PR: https://github.com/foundry-rs/foundry/pull/2416
=> Documenting bit shifting operations

src/cheatcodes/get-code.md
Closes #594
add note about `fs_permission`
=> docs: add permission info to getCode

src/reference/anvil/README.md
Closes #595
update missing anvil flags
=> docs: update anvil reference

src/cheatcodes/assume.md, src/reference/config/testing.md, src/static/config.default.toml
Closes https://github.com/foundry-rs/book/issues/615.
Also took this chance to update `config.default.toml` to better match the output of `forge config`.
=> doc: config fuzz.max_test_rejects

src/SUMMARY.md, src/cheatcodes/README.md, src/cheatcodes/external.md, src/cheatcodes/get-code.md, src/cheatcodes/get-deployed-code.md
=> docs: add getDeployedCode

src/faq.md
=> docs: document install from source

src/reference/forge-std/assertEq.md
=> docs: add assertEqUint

src/reference/forge/evm-options.md
=> docs: document fork-retry-backoff

src/faq.md
=> docs: document solc restrictions

src/faq.md, src/reference/config/solidity-compiler.md
=> docs: document include paths

src/cheatcodes/create-fork.md, src/cheatcodes/roll-fork.md
add documention for new overloaded forking functions
=> docs: document new fork overloaded cheatcodes

src/reference/anvil/README.md
=> docs: document ipc argument

src/cheatcodes/parse-json.md
=> Add jsonPath docs

src/SUMMARY.md, src/cheatcodes/README.md, src/cheatcodes/forking.md, src/cheatcodes/transact.md
Closes #653
ref https://github.com/foundry-rs/foundry/pull/3328
=> docs: document transact cheatcode

src/faq.md
document some funny business with permissions
ref https://github.com/foundry-rs/foundry/issues/3268
=> docs: add info about permission denied os error 13

src/reference/forge-std/console-log.md
Import "forge-std/console.sol" instead of "hardhat/console.sol".
=> Update console-log.md typo

src/reference/forge/forge-script.md
coming back from a hiatus so please bear with me as I get back up to speed!
fixes: https://github.com/foundry-rs/book/issues/629
=> verifier-options.md

src/reference/cast/cast-index.md
Added extra information and reference cast storage to get values
=> Added extra information and reference cast storage to get values

src/reference/cast/cast-storage.md
Reference cast index for mappings
=> Add detail for mapping slots

src/reference/forge-std/startHoax.md
Reverts foundry-rs/book#683
Ref https://github.com/foundry-rs/book/pull/683#discussion_r1005632234
=> Revert "add precision"

src/cheatcodes/get-code.md
@allcontributors I'd love to be included
=> combinidng --> combining

src/SUMMARY.md, src/tutorials/best-practices.md
Leaving this as a draft to collect feedback on the content, cc @odyslam @lucas-manuel @gakonst
=> doc: add best practices

src/cheatcodes/expect-revert.md
Added example expectRever when using a four letter error message.
=> Added example expectRever when using a four letter error message.

src/reference/cast/cast-abi-encode.md
Per https://github.com/foundry-rs/foundry/issues/3706
Just to add more docs information.
=> added example of encoding a struct/tuple/custom type with components

src/tutorials/solmate-nft.md
I ran into this problem described in issue #687. As the tutorial should be as beginner friendly as possible it should really take the user by the hand and tell her what to do.
=> Add instructions for remapping

src/tutorials/best-practices.md
The content of this PR is essentially taken verbatim from a response to my question on Telegram by @mds1, who gave me permission to PR this info into the book :)
=> Expand on using fuzz tests with forks

src/reference/config/solidity-compiler.md, src/static/config.default.toml
https://github.com/foundry-rs/foundry/pull/3784
=> deny warnings documentation

src/reference/config/solidity-compiler.md
closes: https://github.com/foundry-rs/book/issues/627
=> docs: error code string aliases

src/tutorials/best-practices.md
Addresses https://github.com/foundry-rs/book/pull/720#discussion_r1037338405, @odyslam lmk if I misrepresented your approach at all
=> Best practices updates

src/SUMMARY.md, src/reference/cast/cast-sig-event.md, src/reference/cast/cast.md, src/reference/cast/utility-commands.md
Brings docs in line with https://github.com/foundry-rs/foundry/pull/3929
=> docs: add cast sig-event

src/forge/fork-testing.md
=> Correct Alchemy RPC URL in code examples

src/SUMMARY.md, src/reference/cast/cast-compute-address.md, src/reference/cast/cast-create2.md, src/reference/cast/cast.md
=> Document `cast create2`

src/forge/gas-reports.md
Resolves #565 (read the PR but didn't really see much that was missing)
=> Remove link to PR in `gas-reports.md`

src/SUMMARY.md, src/reference/forge/forge-geiger.md, src/reference/forge/forge.md, src/reference/forge/project-commands.md
=> Document `forge geiger`

src/reference/config/formatter.md
Re https://github.com/foundry-rs/foundry/pull/4031
=> Update formatter with "override_spacing"

src/tutorials/solidity-scripting.md
Related to https://github.com/foundry-rs/foundry/issues/3988 and some other wrong expectations that sometimes I see around.
Tried to make a concise explanation on how `forge script` works and what to expect
=> Add high level overview to `solidity-scripting`

src/tutorials/solidity-scripting.md
Onchain simulation is performed in step 2.
=> fix: fix step reference in Solidity Scripting guide

src/cheatcodes/parse-json.md, src/cheatcodes/serialize-json.md
=> fix: Address mds1 comments on json cheatcodes

src/reference/config/doc-generator.md, src/reference/config/formatter.md
Ref https://github.com/foundry-rs/foundry/pull/4106
=> feat: doc ignore config option

src/config/static-analyzers.md
Update the docs according to the behavior documented by @elopez [here](https://github.com/foundry-rs/book/pull/777#discussion_r1071411537).
=> Update Slither docs

src/tutorials/best-practices.md
Some tweaks based on twitter feedback, @jameswenzel let me know if you have anything to add around the `require` portion
=> some best practices tweaks

src/cheatcodes/make-persistent.md
Keeps the Foundry book persistent with Forge Std:
https://github.com/foundry-rs/forge-std/blob/066ff16c5c03e6f931cd041fd366bc4be1fae82a/src/Vm.sol#L390
=> Name args for "markPersistent" signatures

src/reference/cast/cast-block.md
=> fix: remove outdated cast block flags

src/reference/forge-std/console-log.md
referring Issue #803, update import statement as forge-std/src/console.sol in [Console Logging](https://github.com/foundry-rs/book/blob/master/src/reference/forge-std/console-log.md)
=> update console logging (fixes #803)

src/reference/cast/cast-balance.md
=> add ether flag to cast balance

src/cheatcodes/expect-emit.md
According to docs the the 4th arg into exepctEmit should be true if log data shoult be asserted.
=> Assert the log data of the event

src/tutorials/best-practices.md
Closes #761 by specifying the below names are examples and linking to a comprehensive set of recommend and not recommended test names
=> add link to test name examples

src/cheatcodes/README.md, src/cheatcodes/deal.md
added:
// Set the balance of an account for any ERC20 token
function deal(address token, address to, uint256 give) external;
// Alternative signature to update `totalSupply`
function deal(address token, address to, uint256 give, bool adjust) external;
=> add ERC20 version of deal cheatcode

src/static/config.default.toml
Ref https://github.com/foundry-rs/foundry/pull/4466.
=> docs: remove config fuzz max_global_rejects

src/reference/forge-std/console-log.md
Following the PR https://github.com/foundry-rs/foundry/pull/4482#event-8686982243
=> Add `%e` and `%x` doc

projects/cheatcodes/test/EmitContract.t.sol, projects/cheatcodes/test/OwnerUpOnly.t.sol, projects/fuzz_testing/test/Safe.t.sol, projects/fuzz_testing/test/Safe.t.sol.1, projects/fuzz_testing/test/Safe.t.sol.2, projects/fuzz_testing/test/Safe.t.sol.3, projects/test_filters/test/ComplicatedContract.t.sol, projects/writing_tests/test/Basic.t.sol, projects/writing_tests/test/Basic2.t.sol, scripts/generate-output-forge, src/forge/cheatcodes.md, src/forge/fuzz-testing.md, src/forge/writing-tests.md
Issue: https://github.com/foundry-rs/book/issues/842
=> Test Functions Name improvements

src/reference/cast/cast-access-list.md, src/reference/cast/cast-age.md, src/reference/cast/cast-balance.md, src/reference/cast/cast-basefee.md, src/reference/cast/cast-block.md, src/reference/cast/cast-call.md, src/reference/cast/cast-code.md, src/reference/cast/cast-nonce.md, src/reference/cast/cast-proof.md, src/reference/cast/cast-storage.md, src/reference/common/rpc-url-option.md
ref https://github.com/foundry-rs/foundry/pull/4591
=> docs: update cast block-related options

src/SUMMARY.md, src/cheatcodes/tx-gas-price.md
Fixes https://github.com/foundry-rs/book/issues/868
=> ⛽️ added tx.gasprice pranking

src/tutorials/best-practices.md
=> feat: suggest ALL_CAPS_WITH_UNDERSCORES

src/getting-started/installation.md
=> Fix: installation.md

src/README.md, src/SUMMARY.md, src/cheatcodes/README.md, src/contributing.md
I added a section on how to contribute to Foundry. Mostly copied the intro text from https://github.com/foundry-rs/foundry/blob/master/CONTRIBUTING.md and added the links to 2 quick articles i made on how to contribute. A few people already told me they found the articles really useful so I thought it could be helpful to get more people involved.
I thought about copying the articles directly into the book but they are written with my style and a lot of "I ...", "me ..." so it would probably look weird in the book.
=> add contribution guidelines

src/faq.md, src/getting-started/installation.md
Foundryup supports Windows, but only with Git BASH or WSL.
Also add the Foundry README.md installation troubleshooting to faq.md
Refs: foundry-rs/foundry#4847, foundry-rs/foundry#4849
=> Update installation.md and add installation FAQ

src/cheatcodes/get-label.md, src/cheatcodes/utilities.md
Must be merged after https://github.com/foundry-rs/foundry/pull/4770
=> Cheatcodes: add `getLabel` cheatcode

src/cheatcodes/expect-call.md
Follow up for https://github.com/foundry-rs/foundry/pull/4912
=> feat(cheatcodes): document new expect call behavior

src/cheatcodes/expect-emit.md
=> Add simple `expectEmit` to expect-emit.md

src/reference/cast/cast-send.md
CHORE: fix missing --unlocked in cast send
=> fix missing --unlocked in cast send

src/README.md, src/SUMMARY.md, src/getting-started/first-steps.md, src/tutorials/learn-foundry.md
Addition of youtube playlists for learning Foundry , beginner to advanced
=> add: 📽️ Youtube playlists for learning foundry 

src/getting-started/first-steps.md
Updated the message which is pointing to video tutorial links
=> fix video tutorials links message

src/SUMMARY.md, src/cheatcodes/README.md, src/cheatcodes/environment.md, src/cheatcodes/read-callers.md
Complementary pr for foundry-rs/foundry#4884 that adds doc page for the new `readCallers` cheat code
Ps: 
Please let me know if I skipped any other place where I should have added a link to the new page 🙏🏼
=> feat: add `readCallers` cheatcode docs

src/projects/dependencies.md
Otherwise the forge build command fails
=> Update dependencies.md to use an actual contract in solmate-utils

src/SUMMARY.md, src/reference/cast/account-commands.md, src/reference/cast/cast-codesize.md, src/reference/cast/cast.md
Adds documentation for `cast codesize`.
=> docs: Document `cast codesize`

src/reference/anvil/README.md
=> Task: Add default chain id to anvil reference

src/SUMMARY.md, src/cheatcodes/etch.md, src/cheatcodes/get-code.md, src/reference/forge-std/deployCode.md, src/reference/forge-std/deployCodeTo.md, src/reference/forge-std/std-cheats.md
See https://github.com/foundry-rs/forge-std/pull/401.
Document `deployCodeTo`.
=> docs(forge-std): document `deployCodeTo`

src/tutorials/invariant-testing-bonding-curve.md
This is a tutorial of how to do foundry invariant testing. It is illustrated with linear bonding curve example.
=> docs: Invariant Testing: Bonding Curve Tutorial

src/SUMMARY.md, src/reference/cast/cast-logs.md, src/reference/cast/cast.md, src/reference/cast/transaction-commands.md
=> docs: Document `cast logs`

src/reference/forge/forge-script.md
downstream of https://github.com/foundry-rs/foundry/pull/5590
=> feat: add non-interactive script flag docs

src/reference/anvil/README.md
Downstream from https://github.com/foundry-rs/foundry/pull/5391
=> feat(`anvil`): include CREATE2 docs on anvil

src/cheatcodes/environment.md
This is the only link that's in the sidebar but missing in this page.
=> Add txGasPrice link

src/reference/cast/cast-interface.md
Accompanying docs for https://github.com/foundry-rs/foundry/pull/5748
=> feat: Add `cast interface --json` docs

src/tutorials/best-practices.md
cc @PaulRBerg since it links to sablier
=> chore: add info about changing fuzz seed in CI

src/SUMMARY.md, src/reference/cast/cast-wallet-import.md, src/reference/cast/cast-wallet-list.md, src/reference/cast/cast-wallet.md, src/reference/cast/wallet-commands.md, src/reference/common/wallet-options-keystore.md, src/tutorials/best-practices.md
After https://github.com/foundry-rs/foundry/pull/5551 was merged, there was a need to update the book.
Also, inspired by [this post](https://x.com/patrickalphac/status/1701627568082809009) where users were asking where to learn more.
I also added some recommendations on the Best Practices section, also inspired by the post + https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/5
- References for cast
- Updated options
- Added a new section to best practices
=> cast wallet import / list

src/cheatcodes/deal.md
=> 🥢 ~ nit typo in deal demo

src/cheatcodes/sign.md
=> :memo: docs: fix `vm.sign` example

src/SUMMARY.md, src/tutorials/create2-tutorial.md
Hey guys,
apologies for the delay. This turned out to be more difficult than I anticipated.
With reference to issue #1020 , I am submitting a PR that contains a new page under the tutorials section on CREATE2, including a sub-section on fork testing.
My implementation is inspired by [OpenZeppelin's CREATE2 library](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/793d92a3331538d126033cbacb1ee5b8a7d95adc/contracts/utils/Create2.sol), but is different in a few ways.
I look forward to reviewing and improving upon this draft, although I did my best to adhere to the contributor guidelines.
=> Wrote a tutorial for a CREATE2 factory

src/projects/working-on-an-existing-project.md
**Description**
Removes a redundant clause not deleted in #1042
=> fix(projects): Remove Redundant Clause

src/reference/common/multi-wallet-options-keystore.md
Added the `--account` parameter into the multi-wallet-options-keystore.md file.
fixes: #1017
=> Added `--account` to multi-wallet-options

scripts/common, scripts/generate-output, scripts/generate-output-cast, scripts/generate-output-forge, src/output/cast/cast-call, src/output/cheatcodes/forge-test-cheatcodes, src/output/cheatcodes/forge-test-cheatcodes-expectrevert, src/output/cheatcodes/forge-test-cheatcodes-tracing, src/output/cheatcodes/forge-test-simple, src/output/deps/forge-install, src/output/deps/forge-remappings, src/output/deps/tree, src/output/forge_tree/forge-tree, src/output/forge_tree/forge-tree-no-dedupe, src/output/foundry-template/forge-build, src/output/foundry-template/forge-install, src/output/foundry-template/forge-test, src/output/fuzz_testing/forge-test-fail-fuzz, src/output/fuzz_testing/forge-test-no-fuzz, src/output/fuzz_testing/forge-test-success-fuzz, src/output/hello_foundry/forge-build, src/output/hello_foundry/forge-init, src/output/hello_foundry/forge-test, src/output/hello_foundry/tree, src/output/hello_foundry/tree-with-files, src/output/nft_tutorial/forge-test, src/output/test_filters/forge-test-match-contract-and-test, src/output/test_filters/forge-test-match-path
In preparation for adding "--help" generators
=> chore: update scripts and output

src/reference/forge/forge-script.md, src/tutorials/solidity-scripting.md
=> Replace goerli with sepolia

src/tutorials/best-practices.md
Improve formatting of an ordered list with code examples.
=> best-practices.md: fix formatting

.github/workflows/deploy.yml, README.md, book.toml
=> feat: open external links in new tab

src/reference/config/testing.md
Resolves #893 
Super open to feedback, thank you!
=> document `dictionary_weight`

src/reference/ds-test.md
Adds missing assertions to the documentation.
♥️ Thanks @0xJuancito for the heads up.
=> Adds `assertApprox...` assertions.

src/forge/writing-tests.md
- Fixes improper blocks from https://book.getfoundry.sh/forge/writing-tests
=> [fix] Fix broken code blocks

src/reference/anvil/README.md
potential fix https://github.com/foundry-rs/foundry/issues/5953
=> Add valid commands and sample for genesis.json for anvil

src/reference/config/formatter.md
add new options  
amend with additional examples
=> docs(formatter): update with new options

src/SUMMARY.md, src/reference/cast/cast-mktx.md, src/reference/cast/cast-publish.md, src/reference/cast/cast-send.md, src/reference/cast/transaction-commands.md
Added documentation for `cast mktx`.
Ref foundry-rs/foundry#7056
=> feat: document `cast mktx`

src/tutorials/solidity-scripting.md
Changed to present perfect tense ("have created") to accurately reflect the recent completion of the action.
=> Improve grammar: "create" -> "have created"

src/forge/invariant-testing.md
- add Target Interfaces
- update targetArtifactSelector
=> Update invariant docu

src/SUMMARY.md, src/reference/cast/cast-address-zero.md, src/reference/cast/cast.md, src/reference/cast/utility-commands.md
=> docs: add cast az

src/reference/forge/forge-verify-contract.md
add more examples for the oklink verify, replace the verify url with the newest one
=> update oklink related documents

src/reference/anvil/README.md
- fix typos
- more consistent grammar and style (final period, fix default)
- adjust some wording
I noticed we're inconsistent between imperative and third person, but I haven't addressed as I don't know which form we want to use.
=> :memo: Minor typo and style

src/SUMMARY.md, src/projects/soldeer.md, src/tutorials/solidity-scripting.md
Added soldeer documentation to the book, i tried to mimic the `dependencies` section.
=> added soldeer docs

src/reference/config/solidity-compiler.md
added more valid error codes to solidity compiler config reference
error codes fetched from [here](https://github.com/foundry-rs/foundry/blob/master/crates/config/src/error.rs#L151-L197)
=> chore: add valid error codes

src/getting-started/installation.md
Update profile with `release` since `local` was removed
=> Use release profile for installing from sources

src/projects/soldeer.md
Added some extra doc for the new soldeer options: dry-run and warnings for `.dot` files
=> Updating the soldeer doc to add 2 new extra flags

src/reference/cli/forge/coverage.md, src/reference/cli/forge/snapshot.md, src/reference/cli/forge/test.md, src/static/config.default.toml
ref https://github.com/foundry-rs/foundry/pull/8341
=> Update test options, add rerun option

src/reference/forge/forge-coverage.md
ref https://github.com/foundry-rs/foundry/issues/8281#issuecomment-2203322995
=> Add warning re derive_function_end_line lcov feature

src/reference/forge/forge-verify-contract.md
documenting changes added by https://github.com/foundry-rs/foundry/pull/6781
=> docs: add `--via-ir` flag for `forge verify-contract`

src/forge/writing-tests.md
docs for https://github.com/foundry-rs/foundry/pull/8497
=> Update doc: before test setup

src/reference/cast/cast-call.md
=> Add documentation for call --data argument

src/reference/cli/forge/verify-bytecode.md
These changes were introduced in: https://github.com/foundry-rs/foundry/pull/8510
cc: @yash-atreya @zerosnacks
=> docs(verify-bytecode): updating forge verify-bytecode docs.

src/projects/soldeer.md
Added new Soldeer commands to the book.
=> Feat/soldeer 0.3.0 updates

src/tutorials/solmate-nft.md
Closes: https://github.com/foundry-rs/book/issues/1183
=> fix: incorrect link in solmate example

src/tutorials/solidity-scripting.md
Closes: https://github.com/foundry-rs/foundry/issues/8892
=> Document `--sender` as part of the tutorial for `forge script`

src/ci-cd/github-actions.md
-Added GitHub Actions part to fully explain the features and how they can be used with the examples to make it easier for developers to access functionalities in the docs
=> doc: add ci-cd folder and add github-actions to the folder

src/getting-started/installation.md
Reverts foundry-rs/book#1313
Fixed by https://github.com/foundry-rs/foundry/pull/9080
=> Revert "Update installation.md"

src/static/config.default.toml
Closes https://github.com/foundry-rs/foundry/issues/8773
Update book toml sample
=> Update test match configs

src/reference/config/project.md
Reverts foundry-rs/book#1337
https://github.com/foundry-rs/foundry/blob/25598999a2b33ac6ccfa35c347f3c98aba8e0061/crates/config/src/lib.rs#L2155
=> Revert "Update default `out` folder"

src/reference/forge-std/enable_packed_slots.md, src/reference/forge-std/std-storage.md
Enable packed slots are supported in stdStorage
=> Enable packed slots

src/reference/config/formatter.md
reference: https://github.com/foundry-rs/foundry/blob/7538c4ed5a8575f403321d06c52882d3804eab3d/crates/config/src/fmt.rs#L22-L23
=> docs(formatter): add hex_underscore section

src/announcements.md
Related: https://github.com/foundry-rs/foundry/pull/9746
=> chore: bump foundryup version (9746)

src/cheatcodes/gas-snapshots.md
fixing an extra code snippet opener
=> fix: broken code snippet

src/reference/config/solidity-compiler.md, src/static/config.default.toml
optimizer was disabled by default with https://github.com/foundry-rs/foundry/pull/9657
=> Update optimizer settings to reflect latest

src/cheatcodes/expect-revert.md, src/static/config.default.toml
=> Update expect revert sigs, add warning re expect revert depth and next call

src/cheatcodes/sign-delegation.md
=> chore(signDelegation): improve legibility of signatures

src/cheatcodes/gas-snapshots.md
Reflects changes introduced in:
- https://github.com/foundry-rs/foundry/pull/9791
- https://github.com/foundry-rs/foundry/pull/9645
=> chore: update gas snapshot docs

src/forge/deploying.md
Closes https://github.com/foundry-rs/book/issues/1411
=> Add reference to multichain deployment

src/announcements.md
Related PR: https://github.com/foundry-rs/foundry/pull/9802
=> chore: bump `foundryup` version

src/faq.md, src/forge/fork-testing.md
re https://t.me/foundry_support/59340
=> Add EVM version config and FAQ

src/announcements.md
Related: https://github.com/foundry-rs/foundry/pull/9835
=> chore: bump foundryup version

src/cheatcodes/prank.md, src/cheatcodes/start-prank.md
=> Add prank with delegatecall and example

src/guides/deterministic-deployments-using-create2.md
=> fix: mention `always_use_create_2_factory` in guide

src/reference/forge/forge-bind.md
Closes: https://github.com/foundry-rs/book/issues/1470
=> chore: update command reference forge bind to mention alloy instead of ethers-rs

src/reference/forge/forge-coverage.md
Added flag as per this change: https://github.com/foundry-rs/foundry/pull/8321
=> Add --no-match-coverage flag to coverage command docs

src/config/static-analyzers.md
* Adds `aderyn` 
More info(see adeyrn):
https://docs.soliditylang.org/en/v0.8.29/resources.html#solidity-tools
[3rd bullet point]
=> Update static-analyzers.md Add `aderyn`

src/reference/forge/forge-update.md
Companion PR for https://github.com/foundry-rs/foundry/pull/9522
- Explains lockfile behavior
- Demonstrate how to properly update deps pinned to tag/revs
=> docs: foundry.lock

src/reference/anvil/README.md, src/reference/cast/cast-proof.md
Question:
This is a new call and doesn't follow the hardhat documentation as its unique to anvil, do we want to add inline code documentation for it somewhere? It seems currently undocumented
=> docs(anvil): add anvil_reorg

vocs/docs/pages/reference/cheatcodes/etch.mdx, vocs/docs/pages/reference/chisel/overview.md, vocs/docs/pages/reference/forge/forge-tree.mdx
Fix snippets; post vocs migration
=> fix: #include snippets

vocs/docs/public/_redirects, vocs/sidebar/sidebar.ts
=> fix: add cheatcodes ref redirect and fix cast ref link

vocs/docs/pages/forge/deploying.md
=> fix: argument ordering w/ forge deploy

vocs/docs/pages/index.mdx
Initiliazes → Initializes
The rest of the diff is meaningless whitespace
=> chore: typo

vocs/docs/pages/index.mdx, vocs/docs/styles.css
Per https://github.com/foundry-rs/book/pull/1530#issuecomment-2936400988
border is in the accent color, enough to stand out but not enough to distract
=> chore: add announcement button to homepage

vocs/docs/pages/forge/deploying.md
Follow up of https://github.com/foundry-rs/book/pull/1571
=> chore: add additional context re: broadcast flag

vocs/docs/pages/anvil/overview.md
re https://t.me/ethers_rs/45568 add docs on starting Anvil with random mnemonic
=> EIP-7702: start anvil with random mnemonic

vocs/docs/pages/anvil/overview.md, vocs/docs/pages/cast/reference/cast-etherscan-source.mdx, vocs/docs/pages/forge/deploying.md, vocs/docs/pages/guides/scripting-with-solidity.md, vocs/docs/pages/introduction/installation.md
Depends on: https://github.com/foundry-rs/foundry/pull/10902
=> feat: update copy of installation note on verification / integrity check of binaries

vocs/docs/pages/anvil/overview.md, vocs/docs/pages/cast/reference/cast-etherscan-source.mdx, vocs/docs/pages/forge/deploying.md, vocs/docs/pages/guides/scripting-with-solidity.md, vocs/vocs.config.ts
Noticed the diff on https://github.com/foundry-rs/book/pull/1591 is larger than expected due to a force-push that happened to master here: https://github.com/foundry-rs/book/compare/266f8774e29e847471ac02d5386514690486c2c9..f9e27b33dccfd282c8018e08e6ddf243de96b1e2, restoring
=> fix: re-add removed commits

vocs/docs/pages/config/reference/linter.mdx, vocs/docs/pages/forge/linting.md
https://github.com/foundry-rs/foundry/pull/10967
=> doc: unwrapped-modifier-logic lint

vocs/docs/pages/forge/linting.md
https://github.com/foundry-rs/foundry/pull/11046
=> docs: add `unchecked-typecast`

vocs/docs/pages/config/reference/linter.mdx
cc @0xrusowsky
As asked here: https://x.com/siobh_eth/status/1959988063003689201
=> chore: add note on disabling linting on build 

vocs/docs/pages/reference/cheatcodes/write-json.mdx, vocs/docs/pages/reference/cheatcodes/write-toml.mdx
ref:
- https://github.com/foundry-rs/foundry/pull/11447
=> docs(cheats): explain new upsert behavior

.github/CODEOWNERS
now all Foundry repo's have synced code owners
@DaniPopes / @klkvr feel free to ignore / update CODEOWNERS if this feel spammy
=> chore: sync codeowners

.github/dependabot.yml, .github/workflows/deploy.yml, .github/workflows/project.yml, .github/workflows/test.yml, .github/workflows/update.yml
hardens permissions and pins hashes
introduces dependabot to keep hashes up to date on a weekly basis
=> chore(`ci`): harden ci + pin hashes

vocs/docs/pages/anvil/reference.md
The change is based on my observations. May not be fully correct.
=> docs: enhance documentation for evm_setAutomine method

vocs/docs/pages/config/shell-autocompletion.md
- Updated introduction line to include nushell and fig
- Added nushell setup instructions with proper directory structure
Closes #1661
=> chore: add nushell and fig shell autocompletion support
